// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    EventConstructor,
] interface GestureEvent : Event {
    [InitializedByEventConstructor] readonly attribute long primaryPointer;
    [InitializedByEventConstructor] readonly attribute double x;
    [InitializedByEventConstructor] readonly attribute double y;
    [InitializedByEventConstructor] readonly attribute double dx;
    [InitializedByEventConstructor] readonly attribute double dy;
    [InitializedByEventConstructor] readonly attribute double velocityX;
    [InitializedByEventConstructor] readonly attribute double velocityY;
};
