// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import '../data/color.dart';
import '../data/color_dark.dart';
import '../data/color_dark_high_contrast.dart';
import '../data/color_dark_medium_contrast.dart';
import '../data/color_light_high_contrast.dart';
import '../data/color_light_medium_contrast.dart';
import 'template.dart';

class ColorSchemeTemplate extends TokenTemplate {
  const ColorSchemeTemplate(super.blockName, super.fileName);

  @override
  String generate() {
    return '''
const ColorScheme _colorSchemeLightM3E = ColorScheme(
  brightness: Brightness.light,
  primary: Color(${TokenColor.primary}),
  onPrimary: Color(${TokenColor.onPrimary}),
  primaryContainer: Color(${TokenColor.primaryContainer}),
  onPrimaryContainer: Color(${TokenColor.onPrimaryContainer}),
  primaryFixed: Color(${TokenColor.primaryFixed}),
  primaryFixedDim: Color(${TokenColor.primaryFixedDim}),
  onPrimaryFixed: Color(${TokenColor.onPrimaryFixed}),
  onPrimaryFixedVariant: Color(${TokenColor.onPrimaryFixedVariant}),
  secondary: Color(${TokenColor.secondary}),
  onSecondary: Color(${TokenColor.onSecondary}),
  secondaryContainer: Color(${TokenColor.secondaryContainer}),
  onSecondaryContainer: Color(${TokenColor.onSecondaryContainer}),
  secondaryFixed: Color(${TokenColor.secondaryFixed}),
  secondaryFixedDim: Color(${TokenColor.secondaryFixedDim}),
  onSecondaryFixed: Color(${TokenColor.onSecondaryFixed}),
  onSecondaryFixedVariant: Color(${TokenColor.onSecondaryFixedVariant}),
  tertiary: Color(${TokenColor.tertiary}),
  onTertiary: Color(${TokenColor.onTertiary}),
  tertiaryContainer: Color(${TokenColor.tertiaryContainer}),
  onTertiaryContainer: Color(${TokenColor.onTertiaryContainer}),
  tertiaryFixed: Color(${TokenColor.tertiaryFixed}),
  tertiaryFixedDim: Color(${TokenColor.tertiaryFixedDim}),
  onTertiaryFixed: Color(${TokenColor.onTertiaryFixed}),
  onTertiaryFixedVariant: Color(${TokenColor.onTertiaryFixedVariant}),
  error: Color(${TokenColor.error}),
  onError: Color(${TokenColor.onError}),
  errorContainer: Color(${TokenColor.errorContainer}),
  onErrorContainer: Color(${TokenColor.onErrorContainer}),
  background: Color(${TokenColor.background}),
  onBackground: Color(${TokenColor.onBackground}),
  surface: Color(${TokenColor.surface}),
  surfaceBright: Color(${TokenColor.surfaceBright}),
  surfaceContainerLowest: Color(${TokenColor.surfaceContainerLowest}),
  surfaceContainerLow: Color(${TokenColor.surfaceContainerLow}),
  surfaceContainer: Color(${TokenColor.surfaceContainer}),
  surfaceContainerHigh: Color(${TokenColor.surfaceContainerHigh}),
  surfaceContainerHighest: Color(${TokenColor.surfaceContainerHighest}),
  surfaceDim: Color(${TokenColor.surfaceDim}),
  onSurface: Color(${TokenColor.onSurface}),
  surfaceVariant: Color(${TokenColor.surfaceVariant}),
  onSurfaceVariant: Color(${TokenColor.onSurfaceVariant}),
  outline: Color(${TokenColor.outline}),
  outlineVariant: Color(${TokenColor.outlineVariant}),
  shadow: Color(${TokenColor.shadow}),
  scrim: Color(${TokenColor.scrim}),
  inverseSurface: Color(${TokenColor.inverseSurface}),
  onInverseSurface: Color(${TokenColor.inverseOnSurface}),
  inversePrimary: Color(${TokenColor.inversePrimary}),
);

const ColorScheme _colorSchemeDarkM3E = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(${TokenColorDark.primary}),
  onPrimary: Color(${TokenColorDark.onPrimary}),
  primaryContainer: Color(${TokenColorDark.primaryContainer}),
  onPrimaryContainer: Color(${TokenColorDark.onPrimaryContainer}),
  secondary: Color(${TokenColorDark.secondary}),
  onSecondary: Color(${TokenColorDark.onSecondary}),
  secondaryContainer: Color(${TokenColorDark.secondaryContainer}),
  onSecondaryContainer: Color(${TokenColorDark.onSecondaryContainer}),
  tertiary: Color(${TokenColorDark.tertiary}),
  onTertiary: Color(${TokenColorDark.onTertiary}),
  tertiaryContainer: Color(${TokenColorDark.tertiaryContainer}),
  onTertiaryContainer: Color(${TokenColorDark.onTertiaryContainer}),
  error: Color(${TokenColorDark.error}),
  onError: Color(${TokenColorDark.onError}),
  errorContainer: Color(${TokenColorDark.errorContainer}),
  onErrorContainer: Color(${TokenColorDark.onErrorContainer}),
  background: Color(${TokenColorDark.background}),
  onBackground: Color(${TokenColorDark.onBackground}),
  surface: Color(${TokenColorDark.surface}),
  surfaceBright: Color(${TokenColorDark.surfaceBright}),
  surfaceContainerLowest: Color(${TokenColorDark.surfaceContainerLowest}),
  surfaceContainerLow: Color(${TokenColorDark.surfaceContainerLow}),
  surfaceContainer: Color(${TokenColorDark.surfaceContainer}),
  surfaceContainerHigh: Color(${TokenColorDark.surfaceContainerHigh}),
  surfaceContainerHighest: Color(${TokenColorDark.surfaceContainerHighest}),
  surfaceDim: Color(${TokenColorDark.surfaceDim}),
  onSurface: Color(${TokenColorDark.onSurface}),
  surfaceVariant: Color(${TokenColorDark.surfaceVariant}),
  onSurfaceVariant: Color(${TokenColorDark.onSurfaceVariant}),
  outline: Color(${TokenColorDark.outline}),
  outlineVariant: Color(${TokenColorDark.outlineVariant}),
  shadow: Color(${TokenColorDark.shadow}),
  scrim: Color(${TokenColorDark.scrim}),
  inverseSurface: Color(${TokenColorDark.inverseSurface}),
  onInverseSurface: Color(${TokenColorDark.inverseOnSurface}),
  inversePrimary: Color(${TokenColorDark.inversePrimary}),
  // The following color roles have the same values as the roles in the light color scheme _colorSchemeLightM3E.
  primaryFixed: Color(${TokenColor.primaryFixed}),
  primaryFixedDim: Color(${TokenColor.primaryFixedDim}),
  onPrimaryFixed: Color(${TokenColor.onPrimaryFixed}),
  onPrimaryFixedVariant: Color(${TokenColor.onPrimaryFixedVariant}),
  secondaryFixed: Color(${TokenColor.secondaryFixed}),
  secondaryFixedDim: Color(${TokenColor.secondaryFixedDim}),
  onSecondaryFixed: Color(${TokenColor.onSecondaryFixed}),
  onSecondaryFixedVariant: Color(${TokenColor.onSecondaryFixedVariant}),
  tertiaryFixed: Color(${TokenColor.tertiaryFixed}),
  tertiaryFixedDim: Color(${TokenColor.tertiaryFixedDim}),
  onTertiaryFixed: Color(${TokenColor.onTertiaryFixed}),
  onTertiaryFixedVariant: Color(${TokenColor.onTertiaryFixedVariant}),
);

const ColorScheme _colorSchemeLightMediumContrastM3E = ColorScheme(
  brightness: Brightness.light,
  primary: Color(${TokenColorLightMediumContrast.primary}),
  onPrimary: Color(${TokenColorLightMediumContrast.onPrimary}),
  primaryContainer: Color(${TokenColorLightMediumContrast.primaryContainer}),
  onPrimaryContainer: Color(${TokenColorLightMediumContrast.onPrimaryContainer}),
  primaryFixed: Color(${TokenColorLightMediumContrast.primaryFixed}),
  primaryFixedDim: Color(${TokenColorLightMediumContrast.primaryFixedDim}),
  onPrimaryFixed: Color(${TokenColorLightMediumContrast.onPrimaryFixed}),
  onPrimaryFixedVariant: Color(${TokenColorLightMediumContrast.onPrimaryFixedVariant}),
  secondary: Color(${TokenColorLightMediumContrast.secondary}),
  onSecondary: Color(${TokenColorLightMediumContrast.onSecondary}),
  secondaryContainer: Color(${TokenColorLightMediumContrast.secondaryContainer}),
  onSecondaryContainer: Color(${TokenColorLightMediumContrast.onSecondaryContainer}),
  secondaryFixed: Color(${TokenColorLightMediumContrast.secondaryFixed}),
  secondaryFixedDim: Color(${TokenColorLightMediumContrast.secondaryFixedDim}),
  onSecondaryFixed: Color(${TokenColorLightMediumContrast.onSecondaryFixed}),
  onSecondaryFixedVariant: Color(${TokenColorLightMediumContrast.onSecondaryFixedVariant}),
  tertiary: Color(${TokenColorLightMediumContrast.tertiary}),
  onTertiary: Color(${TokenColorLightMediumContrast.onTertiary}),
  tertiaryContainer: Color(${TokenColorLightMediumContrast.tertiaryContainer}),
  onTertiaryContainer: Color(${TokenColorLightMediumContrast.onTertiaryContainer}),
  tertiaryFixed: Color(${TokenColorLightMediumContrast.tertiaryFixed}),
  tertiaryFixedDim: Color(${TokenColorLightMediumContrast.tertiaryFixedDim}),
  onTertiaryFixed: Color(${TokenColorLightMediumContrast.onTertiaryFixed}),
  onTertiaryFixedVariant: Color(${TokenColorLightMediumContrast.onTertiaryFixedVariant}),
  error: Color(${TokenColorLightMediumContrast.error}),
  onError: Color(${TokenColorLightMediumContrast.onError}),
  errorContainer: Color(${TokenColorLightMediumContrast.errorContainer}),
  onErrorContainer: Color(${TokenColorLightMediumContrast.onErrorContainer}),
  onBackground: Color(${TokenColorLightMediumContrast.onBackground}),
  onSurface: Color(${TokenColorLightMediumContrast.onSurface}),
  onSurfaceVariant: Color(${TokenColorLightMediumContrast.onSurfaceVariant}),
  outline: Color(${TokenColorLightMediumContrast.outline}),
  outlineVariant: Color(${TokenColorLightMediumContrast.outlineVariant}),
  onInverseSurface: Color(${TokenColorLightMediumContrast.inverseOnSurface}),
  // The following color roles have the same values as the roles in the light color scheme _colorSchemeLightM3E.
  background: Color(${TokenColor.background}),
  surface: Color(${TokenColor.surface}),
  surfaceBright: Color(${TokenColor.surfaceBright}),
  surfaceContainerLowest: Color(${TokenColor.surfaceContainerLowest}),
  surfaceContainerLow: Color(${TokenColor.surfaceContainerLow}),
  surfaceContainer: Color(${TokenColor.surfaceContainer}),
  surfaceContainerHigh: Color(${TokenColor.surfaceContainerHigh}),
  surfaceContainerHighest: Color(${TokenColor.surfaceContainerHighest}),
  surfaceDim: Color(${TokenColor.surfaceDim}),
  surfaceVariant: Color(${TokenColor.surfaceVariant}),
  shadow: Color(${TokenColor.shadow}),
  scrim: Color(${TokenColor.scrim}),
  inverseSurface: Color(${TokenColor.inverseSurface}),
  inversePrimary: Color(${TokenColor.inversePrimary}),
);

const ColorScheme _colorSchemeLightHighContrastM3E = ColorScheme(
  brightness: Brightness.light,
  primary: Color(${TokenColorLightHighContrast.primary}),
  onPrimary: Color(${TokenColorLightHighContrast.onPrimary}),
  primaryContainer: Color(${TokenColorLightHighContrast.primaryContainer}),
  onPrimaryContainer: Color(${TokenColorLightHighContrast.onPrimaryContainer}),
  primaryFixed: Color(${TokenColorLightHighContrast.primaryFixed}),
  primaryFixedDim: Color(${TokenColorLightHighContrast.primaryFixedDim}),
  onPrimaryFixed: Color(${TokenColorLightHighContrast.onPrimaryFixed}),
  onPrimaryFixedVariant: Color(${TokenColorLightHighContrast.onPrimaryFixedVariant}),
  secondary: Color(${TokenColorLightHighContrast.secondary}),
  onSecondary: Color(${TokenColorLightHighContrast.onSecondary}),
  secondaryContainer: Color(${TokenColorLightHighContrast.secondaryContainer}),
  onSecondaryContainer: Color(${TokenColorLightHighContrast.onSecondaryContainer}),
  secondaryFixed: Color(${TokenColorLightHighContrast.secondaryFixed}),
  secondaryFixedDim: Color(${TokenColorLightHighContrast.secondaryFixedDim}),
  onSecondaryFixed: Color(${TokenColorLightHighContrast.onSecondaryFixed}),
  onSecondaryFixedVariant: Color(${TokenColorLightHighContrast.onSecondaryFixedVariant}),
  tertiary: Color(${TokenColorLightHighContrast.tertiary}),
  onTertiary: Color(${TokenColorLightHighContrast.onTertiary}),
  tertiaryContainer: Color(${TokenColorLightHighContrast.tertiaryContainer}),
  onTertiaryContainer: Color(${TokenColorLightHighContrast.onTertiaryContainer}),
  tertiaryFixed: Color(${TokenColorLightHighContrast.tertiaryFixed}),
  tertiaryFixedDim: Color(${TokenColorLightHighContrast.tertiaryFixedDim}),
  onTertiaryFixed: Color(${TokenColorLightHighContrast.onTertiaryFixed}),
  onTertiaryFixedVariant: Color(${TokenColorLightHighContrast.onTertiaryFixedVariant}),
  error: Color(${TokenColorLightHighContrast.error}),
  onError: Color(${TokenColorLightHighContrast.onError}),
  errorContainer: Color(${TokenColorLightHighContrast.errorContainer}),
  onErrorContainer: Color(${TokenColorLightHighContrast.onErrorContainer}),
  onBackground: Color(${TokenColorLightHighContrast.onBackground}),
  onSurface: Color(${TokenColorLightHighContrast.onSurface}),
  onSurfaceVariant: Color(${TokenColorLightHighContrast.onSurfaceVariant}),
  outline: Color(${TokenColorLightHighContrast.outline}),
  outlineVariant: Color(${TokenColorLightHighContrast.outlineVariant}),
  onInverseSurface: Color(${TokenColorLightHighContrast.inverseOnSurface}),
  // The following color roles have the same values as the roles in the light color scheme _colorSchemeLightM3E.
  background: Color(${TokenColor.background}),
  surface: Color(${TokenColor.surface}),
  surfaceBright: Color(${TokenColor.surfaceBright}),
  surfaceContainerLowest: Color(${TokenColor.surfaceContainerLowest}),
  surfaceContainerLow: Color(${TokenColor.surfaceContainerLow}),
  surfaceContainer: Color(${TokenColor.surfaceContainer}),
  surfaceContainerHigh: Color(${TokenColor.surfaceContainerHigh}),
  surfaceContainerHighest: Color(${TokenColor.surfaceContainerHighest}),
  surfaceDim: Color(${TokenColor.surfaceDim}),
  surfaceVariant: Color(${TokenColor.surfaceVariant}),
  shadow: Color(${TokenColor.shadow}),
  scrim: Color(${TokenColor.scrim}),
  inverseSurface: Color(${TokenColor.inverseSurface}),
  inversePrimary: Color(${TokenColor.inversePrimary}),
);

const ColorScheme _colorSchemeDarkMediumContrastM3E = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(${TokenColorDarkMediumContrast.primary}),
  onPrimary: Color(${TokenColorDarkMediumContrast.onPrimary}),
  primaryContainer: Color(${TokenColorDarkMediumContrast.primaryContainer}),
  onPrimaryContainer: Color(${TokenColorDarkMediumContrast.onPrimaryContainer}),
  primaryFixed: Color(${TokenColorDarkMediumContrast.primaryFixed}),
  primaryFixedDim: Color(${TokenColorDarkMediumContrast.primaryFixedDim}),
  onPrimaryFixed: Color(${TokenColorDarkMediumContrast.onPrimaryFixed}),
  onPrimaryFixedVariant: Color(${TokenColorDarkMediumContrast.onPrimaryFixedVariant}),
  secondary: Color(${TokenColorDarkMediumContrast.secondary}),
  onSecondary: Color(${TokenColorDarkMediumContrast.onSecondary}),
  secondaryContainer: Color(${TokenColorDarkMediumContrast.secondaryContainer}),
  onSecondaryContainer: Color(${TokenColorDarkMediumContrast.onSecondaryContainer}),
  secondaryFixed: Color(${TokenColorDarkMediumContrast.secondaryFixed}),
  secondaryFixedDim: Color(${TokenColorDarkMediumContrast.secondaryFixedDim}),
  onSecondaryFixed: Color(${TokenColorDarkMediumContrast.onSecondaryFixed}),
  onSecondaryFixedVariant: Color(${TokenColorDarkMediumContrast.onSecondaryFixedVariant}),
  tertiary: Color(${TokenColorDarkMediumContrast.tertiary}),
  onTertiary: Color(${TokenColorDarkMediumContrast.onTertiary}),
  tertiaryContainer: Color(${TokenColorDarkMediumContrast.tertiaryContainer}),
  onTertiaryContainer: Color(${TokenColorDarkMediumContrast.onTertiaryContainer}),
  tertiaryFixed: Color(${TokenColorDarkMediumContrast.tertiaryFixed}),
  tertiaryFixedDim: Color(${TokenColorDarkMediumContrast.tertiaryFixedDim}),
  onTertiaryFixed: Color(${TokenColorDarkMediumContrast.onTertiaryFixed}),
  onTertiaryFixedVariant: Color(${TokenColorDarkMediumContrast.onTertiaryFixedVariant}),
  error: Color(${TokenColorDarkMediumContrast.error}),
  onError: Color(${TokenColorDarkMediumContrast.onError}),
  errorContainer: Color(${TokenColorDarkMediumContrast.errorContainer}),
  onErrorContainer: Color(${TokenColorDarkMediumContrast.onErrorContainer}),
  onBackground: Color(${TokenColorDarkMediumContrast.onBackground}),
  onSurface: Color(${TokenColorDarkMediumContrast.onSurface}),
  onSurfaceVariant: Color(${TokenColorDarkMediumContrast.onSurfaceVariant}),
  outline: Color(${TokenColorDarkMediumContrast.outline}),
  outlineVariant: Color(${TokenColorDarkMediumContrast.outlineVariant}),
  onInverseSurface: Color(${TokenColorDarkMediumContrast.inverseOnSurface}),
  inversePrimary: Color(${TokenColorDarkMediumContrast.inversePrimary}),
  // The following color roles have the same values as the roles in the dark color scheme _colorSchemeDarkM3E.
  background: Color(${TokenColorDark.background}),
  surface: Color(${TokenColorDark.surface}),
  surfaceBright: Color(${TokenColorDark.surfaceBright}),
  surfaceContainerLowest: Color(${TokenColorDark.surfaceContainerLowest}),
  surfaceContainerLow: Color(${TokenColorDark.surfaceContainerLow}),
  surfaceContainer: Color(${TokenColorDark.surfaceContainer}),
  surfaceContainerHigh: Color(${TokenColorDark.surfaceContainerHigh}),
  surfaceContainerHighest: Color(${TokenColorDark.surfaceContainerHighest}),
  surfaceDim: Color(${TokenColorDark.surfaceDim}),
  surfaceVariant: Color(${TokenColorDark.surfaceVariant}),
  shadow: Color(${TokenColorDark.shadow}),
  scrim: Color(${TokenColorDark.scrim}),
  inverseSurface: Color(${TokenColorDark.inverseSurface}),
);

const ColorScheme _colorSchemeDarkHighContrastM3E = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(${TokenColorDarkHighContrast.primary}),
  onPrimary: Color(${TokenColorDarkHighContrast.onPrimary}),
  primaryContainer: Color(${TokenColorDarkHighContrast.primaryContainer}),
  onPrimaryContainer: Color(${TokenColorDarkHighContrast.onPrimaryContainer}),
  primaryFixed: Color(${TokenColorDarkHighContrast.primaryFixed}),
  primaryFixedDim: Color(${TokenColorDarkHighContrast.primaryFixedDim}),
  onPrimaryFixed: Color(${TokenColorDarkHighContrast.onPrimaryFixed}),
  onPrimaryFixedVariant: Color(${TokenColorDarkHighContrast.onPrimaryFixedVariant}),
  secondary: Color(${TokenColorDarkHighContrast.secondary}),
  onSecondary: Color(${TokenColorDarkHighContrast.onSecondary}),
  secondaryContainer: Color(${TokenColorDarkHighContrast.secondaryContainer}),
  onSecondaryContainer: Color(${TokenColorDarkHighContrast.onSecondaryContainer}),
  secondaryFixed: Color(${TokenColorDarkHighContrast.secondaryFixed}),
  secondaryFixedDim: Color(${TokenColorDarkHighContrast.secondaryFixedDim}),
  onSecondaryFixed: Color(${TokenColorDarkHighContrast.onSecondaryFixed}),
  onSecondaryFixedVariant: Color(${TokenColorDarkHighContrast.onSecondaryFixedVariant}),
  tertiary: Color(${TokenColorDarkHighContrast.tertiary}),
  onTertiary: Color(${TokenColorDarkHighContrast.onTertiary}),
  tertiaryContainer: Color(${TokenColorDarkHighContrast.tertiaryContainer}),
  onTertiaryContainer: Color(${TokenColorDarkHighContrast.onTertiaryContainer}),
  tertiaryFixed: Color(${TokenColorDarkHighContrast.tertiaryFixed}),
  tertiaryFixedDim: Color(${TokenColorDarkHighContrast.tertiaryFixedDim}),
  onTertiaryFixed: Color(${TokenColorDarkHighContrast.onTertiaryFixed}),
  onTertiaryFixedVariant: Color(${TokenColorDarkHighContrast.onTertiaryFixedVariant}),
  error: Color(${TokenColorDarkHighContrast.error}),
  onError: Color(${TokenColorDarkHighContrast.onError}),
  errorContainer: Color(${TokenColorDarkHighContrast.errorContainer}),
  onErrorContainer: Color(${TokenColorDarkHighContrast.onErrorContainer}),
  onBackground: Color(${TokenColorDarkHighContrast.onBackground}),
  onSurface: Color(${TokenColorDarkHighContrast.onSurface}),
  onSurfaceVariant: Color(${TokenColorDarkHighContrast.onSurfaceVariant}),
  outline: Color(${TokenColorDarkHighContrast.outline}),
  outlineVariant: Color(${TokenColorDarkHighContrast.outlineVariant}),
  onInverseSurface: Color(${TokenColorDarkHighContrast.inverseOnSurface}),
  inversePrimary: Color(${TokenColorDarkHighContrast.inversePrimary}),
  // The following color roles have the same values as the roles in the dark color scheme _colorSchemeDarkM3E.
  background: Color(${TokenColorDark.background}),
  surface: Color(${TokenColorDark.surface}),
  surfaceBright: Color(${TokenColorDark.surfaceBright}),
  surfaceContainerLowest: Color(${TokenColorDark.surfaceContainerLowest}),
  surfaceContainerLow: Color(${TokenColorDark.surfaceContainerLow}),
  surfaceContainer: Color(${TokenColorDark.surfaceContainer}),
  surfaceContainerHigh: Color(${TokenColorDark.surfaceContainerHigh}),
  surfaceContainerHighest: Color(${TokenColorDark.surfaceContainerHighest}),
  surfaceDim: Color(${TokenColorDark.surfaceDim}),
  surfaceVariant: Color(${TokenColorDark.surfaceVariant}),
  shadow: Color(${TokenColorDark.shadow}),
  scrim: Color(${TokenColorDark.scrim}),
  inverseSurface: Color(${TokenColorDark.inverseSurface}),
);
''';
  }
}
