// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    ImplementedAs=CanvasGradient,
    PrivateDart,
    Constructor()
] interface Gradient : Shader {
  void initLinear(Point[] endPoints, Color[] colors, float[] colorStops,
                  TileMode tileMode);
  void initRadial(Point center, double radius, Color[] colors,
                  float[] colorStops, TileMode tileMode);
};
