// Copyright 2013 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
  Constructor(),
  ImplementedAs=CanvasImage,
] interface Image {
    // TODO(ianh): convert this to a Size
    readonly attribute long width;  // width in number of image pixels
    readonly attribute long height; // height in number of image pixels
};
