// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
[
    Constructor()
] interface LayerDrawLooperBuilder {
  // Returns a DrawLooper based on the construction operations, and resets the
  // builder back to a default state.
  DrawLooper build();

  void addLayerOnTop(DrawLooperLayerInfo info, DrawLooperAddLayerCallback callback);
};
