// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
  Constructor(),
  ImplementedAs=CanvasPath,
] interface Path {
    void moveTo(float x, float y);
    void relativeMoveTo(float dx, float dy);
    void lineTo(float x, float y);
    void relativeLineTo(float dx, float dy);
    void quadraticBezierTo(float x1, float y1, float x2, float y2);
    void relativeQuadraticBezierTo(float x1, float y1, float x2, float y2);
    void cubicTo(float x1, float y1, float x2, float y2, float x3, float y3);
    void relativeCubicTo(float x1, float y1, float x2, float y2, float x3, float y3);
    void conicTo(float x1, float y1, float x2, float y2, float w);
    void relativeConicTo(float x1, float y1, float x2, float y2, float w);
    void arcTo(Rect rect, float startAngle, float sweepAngle, boolean forceMoveTo); // angles in radians

    void addRect(Rect rect);
    void addOval(Rect oval);
    void addArc(Rect oval, float startAngle, float sweepAngle);  // angles in radians
    void addRRect(RRect rrect);

    void close();
    void reset();

    Path shift(Offset offset);
};
