# Copyright 2013 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//flutter/common/config.gni")
import("//flutter/testing/testing.gni")

source_set("mock_jni_env") {
  testonly = true

  sources = [ "mock_jni_env.h" ]

  public_configs = [
    "//flutter:config",
    "//flutter/shell/platform/android:jni_headers_config",
  ]
}
