# Copyright 2013 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: githooks
publish_to: none

environment:
  sdk: ^3.11.0-0

resolution: workspace

dependencies:
  args: any
  clang_tidy:
    path: ../../../engine/src/flutter/tools/clang_tidy
  meta: any
  path: any

dependency_overrides:
  clang_tidy:
    path: ../../../engine/src/flutter/tools/clang_tidy
  git_repo_tools:
    path: ../../../engine/src/flutter/tools/pkg/git_repo_tools
  engine_repo_tools:
    path: ../../../engine/src/flutter/tools/pkg/engine_repo_tools
  process_fakes:
    path: ../../../engine/src/flutter/tools/pkg/process_fakes

dev_dependencies:
  test: any

# PUBSPEC CHECKSUM: 7b6nk2
