#!/bin/sh
# Copyright 2013 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
NEW_HOOK="$REPO_ROOT/dev/tools/githooks/$(basename "$0")"

if [ -f "$NEW_HOOK" ]; then
  exec "$NEW_HOOK" "$@"
fi

exit 0
