name: 'Wait for Engine Build'
description: 'Wait for an engine build and redirect engine.version if engine files changed'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  check-name:
    description: 'The name of the check to wait on'
    required: false
    default: 'Linux linux_host_engine'
  check-regexp:
    description: 'Filter checks using regex pattern'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Check Engine Changes
      id: check_engine
      shell: bash
      run: |
        # 1. Determine local base tracking SHA
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          BASE_REF="${{ github.event.pull_request.base.sha }}"
        elif [ "${{ github.event_name }}" = "merge_group" ]; then
          BASE_REF="${{ github.event.merge_group.base_sha }}"
        else
          BASE_REF="origin/master"
        fi

        echo "Comparing against base SHA: $BASE_REF"

        # 2. Get the changed files using the helper script
        CHANGED_FILES=$(.github/scripts/git_files_changed.sh "$BASE_REF")
        echo "Changed files in this branch:"
        echo "$CHANGED_FILES"

        # 3. Check if any file matches engine pattern using the helper script:
        if [ "$(echo "$CHANGED_FILES" | .github/scripts/did_engine_change.sh)" = "true" ]; then
          echo "Engine file changed - forced to wait for check-name: '${{ inputs.check-name }}', check-regexp: '${{ inputs.check-regexp }}'"
          echo "changed=true" >> "$GITHUB_OUTPUT"
        else
          echo "changed=false" >> "$GITHUB_OUTPUT"
        fi

    # Note: lewagon/wait-on-check-action has a limit of 100 checks (pagination).
    # Consider writing an API endpoint on flutter/cocoon that returns the status of an array of checks.
    - name: Wait for test check-in
      if: steps.check_engine.outputs.changed == 'true' && env.ACT != 'true'
      uses: lewagon/wait-on-check-action@9312864dfbc9fd208e9c0417843430751c042800
      with:
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        check-name: ${{ inputs.check-name }}
        check-regexp: ${{ inputs.check-regexp }}
        repo-token: ${{ inputs.github-token }}
        wait-interval: 30 # seconds
        checks-discovery-timeout: 3600 # Wait up to 1 hour for LUCI to register the check
        allowed-conclusions: success,neutral
        verbose: false

    - name: Redirect engine.version
      if: steps.check_engine.outputs.changed == 'true' && github.event_name == 'pull_request'
      shell: bash
      run: |
        echo "FLUTTER_REALM=flutter_archives_v2" >> $GITHUB_ENV
        echo "FLUTTER_PREBUILT_ENGINE_VERSION=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
