# Tests that are excluded from batch Gradle updating and lockfile generation.
# Each exclusion must have an associated reason. Please avoid adding to this list unless necessary,
# as each exclusion must be updated by hand.

# platform_views_layout must be bumped to AGP 9 but it is incompatible with google_mobile_ads 5.1.0
# For more, see: https://github.com/flutter/flutter/issues/185221
- dev/benchmarks/platform_views_layout/android

# The following files must also be manually updated at the moment, because they don't use a
# lib/main.dart (but they don't need exclusion, as we already skip that case).
# dev/benchmarks/microbenchmarks/android/build.gradle
# dev/tracing_tests/android/build.gradle
# dev/integration_tests/external_textures/android/build.gradle
