include: analysis_options_common.yaml

plugins:
  flutter_analyzer_plugin:
    path: dev/flutter_analyzer_plugin
    diagnostics:
      avoid_future_catch_error: true
      no_double_clamp: true
      no_stopwatches: true
      protect_public_state_subtypes: true
      render_box_intrinsics: true

analyzer:
  exclude:
    - "bin/cache/**"
      # Ignore protoc generated files
    - "dev/conductor/lib/proto/*"
    - "engine/**"
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
