/*
 * Copyright (C) 2006, 2007, 2009 Apple Inc. All rights reserved.
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

[
    Custom=Wrap,
    DependentLifetime,
    NotScriptWrappable,
    WillBeGarbageCollected,
] interface CSSValue {

    // UnitTypes
    const unsigned short CSS_INHERIT         = 0;
    const unsigned short CSS_PRIMITIVE_VALUE = 1;
    const unsigned short CSS_VALUE_LIST      = 2;
    const unsigned short CSS_CUSTOM          = 3;

    [RaisesException=Setter] attribute DOMString? cssText;

    readonly attribute unsigned short cssValueType;

};

