// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
[
    GarbageCollected,
] dictionary TestDictionary {
    boolean booleanMember;
    long longMember = 1;
    DOMString stringMember;
    TestInterface testInterfaceMember;
    double? doubleOrNullMember = null;
    DOMString? stringOrNullMember = "default string value";
    TestInterface? testInterfaceOrNullMember;
    TestInterfaceGarbageCollected testInterfaceGarbageCollectedMember;
    TestInterfaceGarbageCollected? testInterfaceGarbageCollectedOrNullMember;
    TestInterfaceWillBeGarbageCollected testInterfaceWillBeGarbageCollectedMember;
    TestInterfaceWillBeGarbageCollected? testInterfaceWillBeGarbageCollectedOrNullMember;
    DOMString[] stringArrayMember;
    sequence<DOMString> stringSequenceMember;
};
