// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// WARNING: Do not edit - generated code.
library dart.sky;

import "dart:nativewrappers";

part 'ANGLEInstancedArrays.dart';
part 'Animation.dart';
part 'AnimationEffect.dart';
part 'AnimationEvent.dart';
part 'AnimationNode.dart';
part 'AnimationPlayer.dart';
part 'AnimationPlayerEvent.dart';
part 'AnimationTimeline.dart';
part 'Attr.dart';
part 'CSS.dart';
part 'CSSMatrix.dart';
part 'CSSStyleDeclaration.dart';
part 'Canvas2DContextAttributes.dart';
part 'CanvasGradient.dart';
part 'CanvasPattern.dart';
part 'CanvasRenderingContext2D.dart';
part 'CharacterData.dart';
part 'ClientRect.dart';
part 'ClientRectList.dart';
part 'CompositionEvent.dart';
part 'DOMError.dart';
part 'DOMException.dart';
part 'DOMTokenList.dart';
part 'Document.dart';
part 'DocumentFragment.dart';
part 'EXTBlendMinMax.dart';
part 'EXTFragDepth.dart';
part 'EXTShaderTextureLOD.dart';
part 'EXTTextureFilterAnisotropic.dart';
part 'Element.dart';
part 'ErrorEvent.dart';
part 'Event.dart';
part 'EventTarget.dart';
part 'FocusEvent.dart';
part 'FontFace.dart';
part 'FontFaceSet.dart';
part 'GestureEvent.dart';
part 'HTMLAnchorElement.dart';
part 'HTMLCanvasElement.dart';
part 'HTMLContentElement.dart';
part 'HTMLElement.dart';
part 'HTMLIFrameElement.dart';
part 'HTMLImageElement.dart';
part 'HTMLImportElement.dart';
part 'HTMLScriptElement.dart';
part 'HTMLStyleElement.dart';
part 'HTMLTElement.dart';
part 'HTMLTemplateElement.dart';
part 'HTMLTitleElement.dart';
part 'HashChangeEvent.dart';
part 'ImageBitmap.dart';
part 'ImageData.dart';
part 'KeyboardEvent.dart';
part 'Location.dart';
part 'MediaQueryList.dart';
part 'MediaQueryListEvent.dart';
part 'MutationObserver.dart';
part 'MutationRecord.dart';
part 'Node.dart';
part 'NodeList.dart';
part 'OESElementIndexUint.dart';
part 'OESStandardDerivatives.dart';
part 'OESTextureFloat.dart';
part 'OESTextureFloatLinear.dart';
part 'OESTextureHalfFloat.dart';
part 'OESTextureHalfFloatLinear.dart';
part 'OESVertexArrayObject.dart';
part 'PageTransitionEvent.dart';
part 'Paint.dart';
part 'PaintingContext.dart';
part 'ParentNode.dart';
part 'Path2D.dart';
part 'PointerEvent.dart';
part 'Range.dart';
part 'Screen.dart';
part 'Selection.dart';
part 'ShadowRoot.dart';
part 'Text.dart';
part 'TextEvent.dart';
part 'TextMetrics.dart';
part 'Timing.dart';
part 'TransitionEvent.dart';
part 'UIEvent.dart';
part 'URL.dart';
part 'WebGLActiveInfo.dart';
part 'WebGLBuffer.dart';
part 'WebGLCompressedTextureATC.dart';
part 'WebGLCompressedTextureETC1.dart';
part 'WebGLCompressedTexturePVRTC.dart';
part 'WebGLCompressedTextureS3TC.dart';
part 'WebGLContextAttributes.dart';
part 'WebGLContextEvent.dart';
part 'WebGLDebugRendererInfo.dart';
part 'WebGLDebugShaders.dart';
part 'WebGLDepthTexture.dart';
part 'WebGLDrawBuffers.dart';
part 'WebGLFramebuffer.dart';
part 'WebGLLoseContext.dart';
part 'WebGLProgram.dart';
part 'WebGLRenderbuffer.dart';
part 'WebGLShader.dart';
part 'WebGLShaderPrecisionFormat.dart';
part 'WebGLTexture.dart';
part 'WebGLUniformLocation.dart';
part 'WebGLVertexArrayObjectOES.dart';
part 'WheelEvent.dart';
part 'Window.dart';

part 'PaintingCallback.dart';
part 'RequestAnimationFrameCallback.dart';
part 'VoidCallback.dart';

Window window;
Document get document => window.document;

typedef EventListener(Event event);
