// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

interface HTMLIFrameElement : HTMLElement {
  [Reflect, URL] attribute DOMString src;

  [CallWith=ScriptState] any takeServicesHandle();
  [CallWith=ScriptState] any takeExposedServicesHandle();
};
