# This Gemfile is for the setup step of the Cirrus Mac tasks
source 'https://rubygems.org'

# If fastlane fails with a wrong Google Cloud dependency, bump this version,
# e.g. https://github.com/flutter/flutter/pull/43362
gem 'fastlane', '2.134.0'

# Don't pin cocoapods so we can catch breakages from upstream changes, e.g.
# https://github.com/flutter/flutter/issues/41144
gem 'cocoapods'
