# When editing this file, update the comment starting "# Gemfile last edited"
# in dev/ci/docker_linux/Dockerfile to retrigger a Docker build on Cirrus.

source "https://rubygems.org"

# Install fastlane which is used on Linux to build and deploy Android
# builds to the Play Store.
gem 'fastlane', '2.134.0'
