name: texture

environment:
  sdk: ^3.12.0-0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any


# PUBSPEC CHECKSUM: f9g2jl
