// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    ConstructorCallWith=ExecutionContext,
    Constructor(Application application, Document document, DOMString url),
] interface Module : AbstractModule {
    readonly attribute Application application;
    [CallWith=ScriptState] attribute any exports;
};
