// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import '../../generic_extension_protocol.dart';
import 'artifacts.dart';

/// The primary coordinator between the tool and extension compilation logic.
abstract base class BuildService extends ToolExtensionService {
  static const String serviceNamespace = 'build';
  static const String getTargetsMethod = 'build.getTargets';
  static const String buildMethod = 'build.build';

  @override
  String get namespace => serviceNamespace;

  /// The set of build targets provided by this extension.
  List<Target> get targets;

  /// Configurations for Dart Build Hooks (build.dart/link.dart).
  Map<String, Object?> get nativeAssetsConfig;

  /// Declares engine artifacts required before building.
  List<ArtifactDependency> get artifactDependencies;

  @override
  Future<Map<String, Function>> initialize() async {
    return <String, Function>{'getTargets': _getTargetsRpc, 'build': _buildRpc};
  }

  @override
  Future<void> shutdown() async {}

  Future<List<Map<String, Object?>>> _getTargetsRpc(Map<String, Object?> params) async {
    return targets.map((Target target) => target.toMap()).toList();
  }

  Future<Map<String, Object?>> _buildRpc(Map<String, Object?> params) async {
    if (params case {
      'targetName': final String targetName,
      'environment': final Map<Object?, Object?> environmentJsonObj,
    }) {
      final BuildEnvironment env;
      try {
        env = BuildEnvironment.fromJson(environmentJsonObj.cast<String, Object?>());
      } on Object catch (e, stackTrace) {
        return BuildResult.failure(
          'Failed to deserialize environment: $e',
          stackTrace: stackTrace.toString(),
        ).toMap();
      }

      final List<Target> matching = targets.where((Target t) => t.name == targetName).toList();
      if (matching.isEmpty) {
        return BuildResult.failure('Target "$targetName" not found.').toMap();
      }
      final Target foundTarget = matching.first;

      try {
        final Map<String, Object?> buildResultMap = await foundTarget.build(env);
        final executablePath = buildResultMap['executablePath'] as String?;
        return BuildResult.success(executablePath: executablePath, extra: buildResultMap).toMap();
      } on Object catch (e, stackTrace) {
        return BuildResult.failure(e.toString(), stackTrace: stackTrace.toString()).toMap();
      }
    }

    return BuildResult.failure(
      'Missing or invalid parameters: targetName must be a String and environment must be a Map.',
    ).toMap();
  }
}

/// A stable, version-checked catalog of core build targets provided by the host tool.
abstract final class CoreBuildTargets {
  static const String kernelSnapshot = 'kernel_snapshot_program';
  static const String aotElf = 'aot_elf_profile';
  static const String webAssets = 'web_release_assets';
  static const String flutterAssets = 'copy_flutter_assets';
}

/// Defines a specific build, bundle, or signing step.
abstract base class Target {
  /// The name of this target.
  String get name;

  /// Optional subcommand name if this target should be registered as a CLI subcommand under `flutter build`.
  String? get cliSubcommand => null;

  /// Optional description for the CLI subcommand when registered under `flutter build`.
  String? get cliDescription => null;

  /// Optional target platform directory name (e.g., 'linux-x64') for structuring output directories to match `flutter run`.
  String? get targetPlatformDirectory => null;

  /// Optional device directory name (e.g., 'linux-proto-1') for structuring output directories to match `flutter run`.
  String? get targetDeviceDirectory => null;

  /// The list of names of dependencies.
  List<String> get dependencies;

  /// Inputs required for this target.
  List<String> get inputs;

  /// Outputs generated by this target.
  List<String> get outputs;

  /// References to depfiles.
  List<Depfile> get depfiles => const <Depfile>[];

  /// Executes target operations.
  /// Returns a map of custom build results (e.g. executablePath).
  Future<Map<String, Object?>> build(BuildEnvironment env);

  /// Custom defines passed back to the tool.
  Future<Map<String, String>> get extraDefines async => const <String, String>{};

  /// Serializes target metadata for transmission over GEP RPC.
  Map<String, Object?> toMap() => <String, Object?>{
    'name': name,
    'dependencies': dependencies,
    'inputs': inputs,
    'outputs': outputs,
    if (cliSubcommand != null) 'cliSubcommand': cliSubcommand,
    if (cliDescription != null) 'cliDescription': cliDescription,
    if (targetPlatformDirectory != null) 'targetPlatformDirectory': targetPlatformDirectory,
    if (targetDeviceDirectory != null) 'targetDeviceDirectory': targetDeviceDirectory,
  };
}

/// A concrete implementation of [Target] that can be parsed from a JSON map returned over GEP RPC.
final class ExtensionBuildTarget extends Target {
  ExtensionBuildTarget.fromJson(Map<String, Object?> json)
    : name = json['name']! as String,
      dependencies = json['dependencies'] is List
          ? (json['dependencies']! as List<Object?>).cast<String>()
          : const <String>[],
      inputs = json['inputs'] is List
          ? (json['inputs']! as List<Object?>).cast<String>()
          : const <String>[],
      outputs = json['outputs'] is List
          ? (json['outputs']! as List<Object?>).cast<String>()
          : const <String>[],
      cliSubcommand = json['cliSubcommand'] as String?,
      cliDescription = json['cliDescription'] as String?,
      targetPlatformDirectory = json['targetPlatformDirectory'] as String?,
      targetDeviceDirectory = json['targetDeviceDirectory'] as String?;

  /// Parse a list of [ExtensionBuildTarget] from an RPC response.
  static List<ExtensionBuildTarget> listFromJson(Object? rpcResult) => [
    if (rpcResult case final List<Object?> l)
      for (final item in l)
        if (item case final Map<Object?, Object?> m)
          ExtensionBuildTarget.fromJson(m.cast<String, Object?>()),
  ];

  @override
  final String name;

  @override
  final List<String> dependencies;

  @override
  final List<String> inputs;

  @override
  final List<String> outputs;

  @override
  final String? cliSubcommand;

  @override
  final String? cliDescription;

  @override
  final String? targetPlatformDirectory;

  @override
  final String? targetDeviceDirectory;

  @override
  Future<Map<String, Object?>> build(BuildEnvironment env) async {
    throw UnimplementedError(
      'ExtensionBuildTarget.build should not be called directly on host representation.',
    );
  }
}

/// Environment state provided by the tool.
class BuildEnvironment {
  BuildEnvironment({
    required this.cacheDir,
    required this.defines,
    required this.flutterAssetsDir,
    required this.outputDirectory,
    required this.projectRoot,
  });

  /// Create a BuildEnvironment from a JSON map.
  factory BuildEnvironment.fromJson(Map<String, Object?> json) {
    return BuildEnvironment(
      cacheDir: Uri.parse(json['cacheDir']! as String),
      defines: (json['defines']! as Map<Object?, Object?>).cast<String, String>(),
      flutterAssetsDir: Uri.parse(json['flutterAssetsDir']! as String),
      outputDirectory: Uri.parse(json['outputDirectory']! as String),
      projectRoot: Uri.parse(json['projectRoot']! as String),
    );
  }

  /// Defines passed to compilation targets.
  final Map<String, String> defines;

  /// Directory holding cached files.
  final Uri cacheDir;

  /// Root directory of the project.
  final Uri projectRoot;

  /// Output directory.
  final Uri outputDirectory;

  /// Assets directory.
  final Uri flutterAssetsDir;

  /// Convert the BuildEnvironment to a JSON-compatible map.
  Map<String, Object?> toMap() => <String, Object?>{
    'cacheDir': cacheDir.toString(),
    'defines': defines,
    'flutterAssetsDir': flutterAssetsDir.toString(),
    'outputDirectory': outputDirectory.toString(),
    'projectRoot': projectRoot.toString(),
  };
}

/// A class for representing depfile formats.
class Depfile {
  /// Create a [Depfile] from a list of [inputs] and [outputs].
  const Depfile(this.inputs, this.outputs);

  /// Inputs in the depfile.
  final List<String> inputs;

  /// Outputs in the depfile.
  final List<String> outputs;
}

/// Result returned by executing a build target over RPC or locally.
final class BuildResult {
  BuildResult.success({this.executablePath, Map<String, Object?>? extra})
    : success = true,
      errorMessage = null,
      stackTrace = null,
      extraData = extra ?? const <String, Object?>{};

  BuildResult.failure(this.errorMessage, {this.stackTrace})
    : success = false,
      executablePath = null,
      extraData = const <String, Object?>{};

  factory BuildResult.fromJson(Map<String, Object?> json) {
    final success = json['success']! as bool;
    if (success) {
      final executablePath = json['executablePath'] as String?;
      final extra = <String, Object?>{};
      for (final MapEntry<String, Object?> entry in json.entries) {
        if (entry.key != 'success' && entry.key != 'executablePath') {
          extra[entry.key] = entry.value;
        }
      }
      return BuildResult.success(executablePath: executablePath, extra: extra);
    }
    return BuildResult.failure(
      json['errorMessage'] as String? ?? 'Unknown error',
      stackTrace: json['stackTrace'] as String?,
    );
  }

  final bool success;
  final String? errorMessage;
  final String? stackTrace;
  final String? executablePath;
  final Map<String, Object?> extraData;

  Map<String, Object?> toMap() => <String, Object?>{
    'success': success,
    if (executablePath != null) 'executablePath': executablePath,
    if (errorMessage != null) 'errorMessage': errorMessage,
    if (stackTrace != null) 'stackTrace': stackTrace,
    ...extraData,
  };

  static List<BuildResult> listFromJson(Object? rpcResult) => [
    if (rpcResult case final List<Object?> l)
      for (final item in l)
        if (item case final Map<Object?, Object?> m)
          BuildResult.fromJson(m.cast<String, Object?>()),
  ];
}
