// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:convert';

import 'package:archive/archive.dart';
import 'package:file/file.dart';
import 'package:file_testing/file_testing.dart';
import 'package:flutter_tools/src/base/io.dart';

import '../src/common.dart';
import 'test_utils.dart';

// The Gradle wrapper launcher (gradlew, gradlew.bat and gradle-wrapper.jar)
// that the tool injects into Android projects must grant native access to the
// JVM it starts. Otherwise JDK 24+ prints JEP 472 warnings on every Gradle run,
// and future JDKs that deny native access by default fail the build.
//
// Launchers generated by Gradle 8.14 or newer do this by starting the wrapper
// jar with `-jar`, so the JVM honors its `Enable-Native-Access` manifest
// attribute. See https://github.com/gradle/gradle/issues/31625.
void main() {
  late Directory tempDir;

  setUp(() {
    tempDir = createResolvedTempDirectorySync('gradle_wrapper_test.');
  });

  tearDown(() {
    tryToDelete(tempDir);
  });

  testWithoutContext('injected Gradle wrapper grants native access', () async {
    final ProcessResult result = await processManager.run(<String>[
      flutterBin,
      'create',
      tempDir.path,
      '--project-name=testapp',
      '--platforms=android',
    ], workingDirectory: tempDir.path);
    expect(result.exitCode, 0, reason: 'stdout: ${result.stdout}\nstderr: ${result.stderr}');

    final Directory androidDir = tempDir.childDirectory('android');

    final File wrapperJar = androidDir
        .childDirectory('gradle')
        .childDirectory('wrapper')
        .childFile('gradle-wrapper.jar');
    expect(wrapperJar, exists);
    final Archive jar = ZipDecoder().decodeBytes(wrapperJar.readAsBytesSync());
    final ArchiveFile? manifest = jar.findFile('META-INF/MANIFEST.MF');
    expect(manifest, isNotNull);
    expect(
      utf8.decode(manifest!.content as List<int>),
      contains('Enable-Native-Access: ALL-UNNAMED'),
    );

    final File gradlew = androidDir.childFile('gradlew');
    expect(gradlew, exists);
    expect(
      gradlew.readAsStringSync(),
      contains(r'-jar "$APP_HOME/gradle/wrapper/gradle-wrapper.jar"'),
    );

    final File gradlewBat = androidDir.childFile('gradlew.bat');
    expect(gradlewBat, exists);
    expect(
      gradlewBat.readAsStringSync(),
      contains(r'-jar "%APP_HOME%\gradle\wrapper\gradle-wrapper.jar"'),
    );
  });
}
