// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/// The two weights of the `RobotoFromHook` family that `hook/build.dart`
/// writes into its output directory and registers as font assets, encoded as
/// base64 so that this repository does not have to contain binary files.
///
/// They are subsets of `Roboto-Regular.ttf` and `Roboto-Bold.ttf` from the
/// Flutter SDK (https://github.com/googlefonts/roboto, Apache License 2.0)
/// with only the glyphs of the word "hook", produced with the SDK's
/// `font-subset` tool.
library;

/// Roboto Regular, glyphs `h`, `k` and `o`.
const String kRobotoRegularFontBase64 =
    'AAEAAAAPAIAAAwBwT1MvMnRvghoAAAJoAAAAYGNtYXAAfwFBAAAB0AAAAERjdnQgK6gHnQAAAhQA'
    'AABUZnBnbXf4YKsAAAUoAAABvGdhc3AACAATAAABCAAAAAxnbHlmm9QWxQAABuQAAAHYaGRteA4K'
    'BA4AAAEUAAAAEGhlYWT8atJ6AAABmAAAADZoaGVhCroFpAAAAXQAAAAkaG10eBCSAdgAAAEkAAAA'
    'EGxvY2EBMgCdAAAA/AAAAAptYXhwAjQDCQAAATQAAAAgbmFtZRIELQQAAALIAAABFHBvc3T/bQBk'
    'AAABVAAAACBwcmVwomb6yQAAA9wAAAFJAAAAAABGAJ0A7AAAAAEAAgAIAAL//wAPAAAAAQAAAAgJ'
    'BQQFBQUAAAOMAGQEaACMBA4AjQSQAFsAAQAAAAQAjwAWAFQABQABAAAAAAAOAAACAAIkAAYAAQAD'
    'AAAAAAAA/2oAZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAds/gwAAAlJ+hv+SgkwAAEAAAAAAAAA'
    'AAAAAAAAAAAEAAEAAAACIxJ4oEfFXw889QAZCAAAAAAAxPARLgAAAADVAVL0+hv91QkwCHMAAAAJ'
    'AAIAAAAAAAAAAAACAAAAAwAAABQAAwABAAAAFAAEADAAAAAIAAgAAgAAAGgAawBv//8AAABoAGsA'
    'b////5n/l/+UAAEAAAAAAAAAAAAqAJ0AgACKAHgA1ABkAE4AWgCHAGAAVgA0AjwAvACyAI4AxAAA'
    'ABT+YAAUApsAIAMhAAsEOgAUBI0AEAWwABQGGAAVAaYAEQbAAA4G2QAGAAAAAAADBIYBkAAFAAAF'
    'mgUzAAABHwWaBTMAAAPRAGYCAAAAAgAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAABHT09HAEAAaABv'
    'BgD+AABmB5oCACAAAZ8AAAAABDoFsAAgACAAAwAAAAcAWgADAAEECQAAAF4AXAADAAEECQABAAwA'
    'UAADAAEECQACAA4AQgADAAEECQADAAwAUAADAAEECQAEAAwAUAADAAEECQAFACYAHAADAAEECQAG'
    'ABwAAABSAG8AYgBvAHQAbwAtAFIAZQBnAHUAbABhAHIAVgBlAHIAcwBpAG8AbgAgADIALgAxADMA'
    'NwA7ACAAMgAwADEANwBSAGUAZwB1AGwAYQByAFIAbwBiAG8AdABvAEMAbwBwAHkAcgBpAGcAaAB0'
    'ACAAMgAwADEAMQAgAEcAbwBvAGcAbABlACAASQBuAGMALgAgAEEAbABsACAAUgBpAGcAaAB0AHMA'
    'IABSAGUAcwBlAHIAdgBlAGQALrAMK7AAKwCyARACKwGyEQECKwG3ETowJRsQAAgrALcBSDsuIRQA'
    'CCu3AlhIOCgUAAgrtwNSQzQlFgAIK7cEXk08KxkACCu3BTYsIhkPAAgrtwZxXUYyGwAIK7cHkXdc'
    'OiMACCu3CH5nUDkaAAgrtwlURTYmFAAIK7cKdmBLNh0ACCu3C4NkTjojAAgrtwzZsopjPAAIK7cN'
    'FBAMCQYACCu3DjwyJxwRAAgrtw9ANCkdFAAIK7cQUEEuIRQACCsAshILByuwACBFfWkYRLI/GgFz'
    'sl8aAXOyfxoBc7IvGgF0sk8aAXSybxoBdLKPGgF0sq8aAXSy/xoBdLIfGgF1sj8aAXWyXxoBdbJ/'
    'GgF1sg8eAXOyfx4Bc7LvHgFzsh8eAXSyXx4BdLKPHgF0ss8eAXSy/x4BdLI/HgF1sm8eAXWyLyAB'
    'c7JvIAFzAAAAsAAsS7AJUFixAQGOWbgB/4WwhB2xCQNfXi2wASwgIEVpRLABYC2wAiywASohLbAD'
    'LCBGsAMlRlJYI1kgiiCKSWSKIEYgaGFksAQlRiBoYWRSWCNlilkvILAAU1hpILAAVFghsEBZG2kg'
    'sABUWCGwQGVZWTotsAQsIEawBCVGUlgjilkgRiBqYWSwBCVGIGphZFJYI4pZL/0tsAUsSyCwAyZQ'
    'WFFYsIBEG7BARFkbISEgRbDAUFiwwEQbIVlZLbAGLCAgRWlEsAFgICBFfWkYRLABYC2wByywBiot'
    'sAgsSyCwAyZTWLBAG7AAWYqKILADJlNYIyGwgIqKG4ojWSCwAyZTWCMhsMCKihuKI1kgsAMmU1gj'
    'IbgBAIqKG4ojWSCwAyZTWCMhuAFAioobiiNZILADJlNYsAMlRbgBgFBYIyG4AYAjIRuwAyVFIyEj'
    'IVkbIVlELbAJLEtTWEVEGyEhWS2wCiywKEUtsAsssClFLbAMLLEnAYggilNYuUAABABjuAgAiFRY'
    'uQAoA+hwWRuwI1NYsCCIuBAAVFi5ACgD6HBZWVktsA0ssECIuCAAWlixKQBEG7kAKQPoRFktAAEA'
    'jAAAA98GAAARAEqyChITERI5ALAQL7AARViwAi8bsQIaPlmwAEVYsAUvG7EFEj5ZsABFWLAOLxux'
    'DhI+WbIAAgUREjmwAhCxCgGwCitYIdgb9FkwMQE2MyATESMRJiYjIgYHESMRMwFFe8UBVwO5AWlv'
    'WogmubkDt5f+ff01Asx1cGBO/P0GAAAAAQCNAAAEDAYAAAwAdQCwAEVYsAQvG7EEID5ZsABFWLAI'
    'LxuxCBo+WbAARViwAi8bsQISPlmwAEVYsAsvG7ELEj5ZsgAIAhESOUAVOgBKAFoAagB6AIoAmgCq'
    'ALoAygAKXbIGCAIREjlAFTYGRgZWBmYGdgaGBpYGpga2BsYGCl0wMQEHESMRMxE3ATMBASMBunS5'
    'uWMBUeH+WwHW2QH1ef6EBgD8X3cBZP48/YoAAgBb/+wENAROAA8AGwBFsgwcHRESObAMELAT0ACw'
    'AEVYsAQvG7EEGj5ZsABFWLAMLxuxDBI+WbETAbAKK1gh2Bv0WbAEELEZAbAKK1gh2Bv0WTAxEzQ2'
    'NjMyABUVFAYGIyIANRcUFjMyNjU0JiMiBlt934/dARF54ZLc/u+6p4yNpqmMiagCJ5/+iv7O/g2e'
    '+4wBMvwJtNrdx7Ld2g==';

/// Roboto Bold, glyphs `h`, `k` and `o`.
const String kRobotoBoldFontBase64 =
    'AAEAAAAPAIAAAwBwT1MvMnWbghsAAAJcAAAAYGNtYXAAfwFBAAAB0AAAAERjdnQgK34EtQAAAhQA'
    'AABIZnBnbV/yGqsAAAa0AAABvGdhc3AACAATAAABCAAAAAxnbHlmk9sZnQAABQgAAAGsaGRteA4K'
    'BA4AAAEUAAAAEGhlYWT819JcAAABmAAAADZoaGVhCyYF0AAAAXQAAAAkaG10eBDSAX0AAAEkAAAA'
    'EGxvY2EBGwCGAAAA/AAAAAptYXhwAjQDEQAAATQAAAAgbmFtZRLGLbQAAAK8AAABHnBvc3T/bQBk'
    'AAABVAAAACBwcmVwKnY2MAAAA9wAAAEpAAAAAABFAIYA1gAAAAEAAgAIAAL//wAPAAAAAQAAAAgJ'
    'BQQFBQUAAAOMAGQEegBoBEYAbwSGAEIAAQAAAAQAjwAWAE4ABQABAAAAAAAOAAACAAIyAAYAAQAD'
    'AAAAAAAA/2oAZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAds/gwAAAmK+jD+NQmHAAEAAAAAAAAA'
    'AAAAAAAAAAAEAAEAAAACIxKi9F0jXw889QAZCAAAAAAAxPARLgAAAADVAVLW+jD91QmHCHMAAQAJ'
    'AAIAAAAAAAAAAAACAAAAAwAAABQAAwABAAAAFAAEADAAAAAIAAgAAgAAAGgAawBv//8AAABoAGsA'
    'b////5n/l/+UAAEAAAAAAAAAAAAqAOkApAD+AE4AYAExAKwAxQDUAHwALQAAABT+YAAUApsAIAMh'
    'AAsEOgAUBI0AEAWwABQGGAAVAaYAEQbAAA4G3wACAAAAAAADBKcCvAAFAAAFmgUzAAABHwWaBTMA'
    'AAPRAGYCAAAAAgAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAABHT09HACAAaABvBgD+AABmB5oCACAA'
    'AZ8AAAAABDoFsAAgACAAAwAAAAcAWgADAAEECQAAAF4AZgADAAEECQABAAwAWgADAAEECQACAAgA'
    'UgADAAEECQADABYAPAADAAEECQAEABYAPAADAAEECQAFACYAFgADAAEECQAGABYAAABSAG8AYgBv'
    'AHQAbwAtAEIAbwBsAGQAVgBlAHIAcwBpAG8AbgAgADIALgAxADMANwA7ACAAMgAwADEANwBSAG8A'
    'YgBvAHQAbwAgAEIAbwBsAGQAQgBvAGwAZABSAG8AYgBvAHQAbwBDAG8AcAB5AHIAaQBnAGgAdAAg'
    'ADIAMAAxADEAIABHAG8AbwBnAGwAZQAgAEkAbgBjAC4AIABBAGwAbAAgAFIAaQBnAGgAdABzACAA'
    'UgBlAHMAZQByAHYAZQBkAC4AALAMK7AAKwCyAQsCKwC3ATEoHxYOAAgrtwJEOiwgEgAIK7cDMSgf'
    'Fg4ACCu3BJF3XDojAAgrtwV2YEs2HQAIK7cGJR8YEQsACCu3B0I2Kh4SAAgrtwg6LyIYDwAIK7cJ'
    'NiwiGA8ACCu3CltLOioZAAgrtwv7zaByRQAIKwCyDAsHK7AAIEV9aRhEsjAOAXOysBABc7JQEAF0'
    'soAQAXSycBABdbI/FAFzsl8UAXOyfxQBc7IvFAF0sk8UAXSybxQBdLKPFAF0sq8UAXSy/xQBdLIf'
    'FAF1sj8UAXWyXxQBdbJ/FAF1sg8YAXOybxgBdbJ/GAFzsu8YAXOyHxgBdLJfGAF0so8YAXSyzxgB'
    'dLL/GAF0sj8YAXWyLxoBc7JvGgFzsi8gAXOyPyABcwAAAAABAGgAAAQPBgAAEABKsgoREhESOQCw'
    'EC+wAEVYsAIvG7ECFD5ZsABFWLAFLxuxBQw+WbAARViwDS8bsQ0MPlmyAAIFERI5sAIQsQoBsAor'
    'WCHYG/RZMDEBNjMgExEhETQmIyIHESERIQGJc64BYAX+31Bdfzn+3wEhA8SK/mf9SwKtXVli/P8G'
    'AAABAG8AAARaBgAADABFALAARViwBC8bsQQaPlmwAEVYsAgvG7EIFD5ZsABFWLACLxuxAgw+WbAA'
    'RViwCy8bsQsMPlmyAAgCERI5sgYIAhESOTAxAQcRIREhETcBIQEBIQH4aP7fASE4ARUBW/55Aan+'
    'tAGyaP62BgD8rUgBRf49/YkAAgBC/+wEQwROAA0AGQBFshEaGxESObARELAE0ACwAEVYsAQvG7EE'
    'FD5ZsABFWLALLxuxCww+WbERAbAKK1gh2Bv0WbAEELEXAbAKK1gh2Bv0WTAxEzQ2NjMyABcXFAAg'
    'ABEFFBYzMjY1NCYjIgZCfOma2wEVEAL+6v4s/ukBIXRsaXZ2a2p0Aieh/Ir+9OZK+f7TASwBAgia'
    'o6Gxl6alsAAsS7AJUFixAQGOWbgB/4WwRB2xCQNfXi2wASwgIEVpRLABYC2wAiywASohLbADLCBG'
    'sAMlRlJYI1kgiiCKSWSKIEYgaGFksAQlRiBoYWRSWCNlilkvILAAU1hpILAAVFghsEBZG2kgsABU'
    'WCGwQGVZWTotsAQsIEawBCVGUlgjilkgRiBqYWSwBCVGIGphZFJYI4pZL/0tsAUsSyCwAyZQWFFY'
    'sIBEG7BARFkbISEgRbDAUFiwwEQbIVlZLbAGLCAgRWlEsAFgICBFfWkYRLABYC2wByywBiotsAgs'
    'SyCwAyZTWLBAG7AAWYqKILADJlNYIyGwgIqKG4ojWSCwAyZTWCMhsMCKihuKI1kgsAMmU1gjIbgB'
    'AIqKG4ojWSCwAyZTWCMhuAFAioobiiNZILADJlNYsAMlRbgBgFBYIyG4AYAjIRuwAyVFIyEjIVkb'
    'IVlELbAJLEtTWEVEGyEhWS2wCiywIkUtsAsssCNFLbAMLLEnAYggilNYuUAABABjuAgAiFRYuQAi'
    'A+hwWRuwI1NYsCCIuBAAVFi5ACID6HBZWVktsA0ssECIuCAAWlixIwBEG7kAIwPoRFkt';
