# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

target 'Runner' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for Runner
  pod 'MaterialControls', '~> 1.2.2'

end
