import 'training_profile.dart';

class ExerciseKnowledgeItem {
  const ExerciseKnowledgeItem({
    required this.id,
    required this.name,
    required this.primaryMuscle,
    required this.movementPattern,
    required this.equipment,
    required this.tags,
    required this.function,
    this.alternative,
  });

  final String id;
  final String name;
  final String primaryMuscle;
  final String movementPattern;
  final EquipmentAccess equipment;
  final Set<String> tags;
  final String function;
  final String? alternative;
}

const List<ExerciseKnowledgeItem> exerciseKnowledge = <ExerciseKnowledgeItem>[
  ExerciseKnowledgeItem(
    id: 'EX0130',
    name: 'Back Squat',
    primaryMuscle: 'Legs',
    movementPattern: 'squat',
    equipment: EquipmentAccess.fullGym,
    tags: <String>{'strength_main', 'hypertrophy_main', 'lower'},
    function: 'Basissquat til styrke og underkropsudvikling.',
    alternative: 'Goblet Squat',
  ),
  ExerciseKnowledgeItem(
    id: 'EX0137',
    name: 'Bulgarian Split Squat',
    primaryMuscle: 'Legs',
    movementPattern: 'unilateral',
    equipment: EquipmentAccess.dumbbells,
    tags: <String>{'hypertrophy_accessory', 'general_support', 'lower'},
    function: 'Ensidig benstyrke og hoftekontrol.',
    alternative: 'Reverse Lunge',
  ),
  ExerciseKnowledgeItem(
    id: 'EX0019',
    name: 'Incline Dumbbell Bench Press',
    primaryMuscle: 'Chest',
    movementPattern: 'horizontal_press',
    equipment: EquipmentAccess.dumbbells,
    tags: <String>{'hypertrophy_main', 'general_main', 'upper_press'},
    function: 'Presvariant med stor ROM og fokus på øvre bryst.',
    alternative: 'Push-Up',
  ),
  ExerciseKnowledgeItem(
    id: 'EX0002',
    name: 'Barbell Bench Press',
    primaryMuscle: 'Chest',
    movementPattern: 'horizontal_press',
    equipment: EquipmentAccess.fullGym,
    tags: <String>{'strength_main', 'upper_press'},
    function: 'Tung presbasis med høj specificitet for styrke.',
    alternative: 'Dumbbell Bench Press',
  ),
  ExerciseKnowledgeItem(
    id: 'EX0073',
    name: 'Romanian Deadlift',
    primaryMuscle: 'Hamstrings',
    movementPattern: 'hinge',
    equipment: EquipmentAccess.fullGym,
    tags: <String>{'strength_support', 'hypertrophy_support', 'lower'},
    function: 'Hinge-bevægelse med stærk bagkædebelastning.',
    alternative: 'Dumbbell Romanian Deadlift',
  ),
  ExerciseKnowledgeItem(
    id: 'EX0076',
    name: 'Seated Cable Row',
    primaryMuscle: 'Back',
    movementPattern: 'horizontal_pull',
    equipment: EquipmentAccess.fullGym,
    tags: <String>{'strength_support', 'hypertrophy_support', 'upper_pull'},
    function: 'Kontrolleret row med konstant spænding.',
    alternative: 'Single-Arm Dumbbell Row',
  ),
  ExerciseKnowledgeItem(
    id: 'EX0060',
    name: 'Lat Pulldown',
    primaryMuscle: 'Back',
    movementPattern: 'vertical_pull',
    equipment: EquipmentAccess.fullGym,
    tags: <String>{'general_support', 'hypertrophy_support', 'upper_pull'},
    function: 'Vertikalt træk der er let at dosere.',
    alternative: 'Assisted Pull-Up',
  ),
  ExerciseKnowledgeItem(
    id: 'EX0107',
    name: 'Dumbbell Lateral Raise',
    primaryMuscle: 'Shoulders',
    movementPattern: 'abduction',
    equipment: EquipmentAccess.dumbbells,
    tags: <String>{'hypertrophy_accessory', 'upper_accessory'},
    function: 'Skulderisolering for side-delt.',
    alternative: 'Cable Lateral Raise',
  ),
  ExerciseKnowledgeItem(
    id: 'EX0085',
    name: 'Straight-Arm Pulldown',
    primaryMuscle: 'Back',
    movementPattern: 'shoulder_extension',
    equipment: EquipmentAccess.fullGym,
    tags: <String>{'hypertrophy_accessory', 'upper_accessory'},
    function: 'Lat-isolation uden høj bicepsbelastning.',
    alternative: 'Band Pulldown',
  ),
  ExerciseKnowledgeItem(
    id: 'EX0028',
    name: 'Push-Up',
    primaryMuscle: 'Chest',
    movementPattern: 'horizontal_press',
    equipment: EquipmentAccess.bodyweight,
    tags: <String>{'general_main', 'bodyweight_main', 'upper_press'},
    function: 'Basispres der er let at skalere.',
    alternative: 'Incline Push-Up',
  ),
  ExerciseKnowledgeItem(
    id: 'EX0052',
    name: 'Dumbbell Row',
    primaryMuscle: 'Back',
    movementPattern: 'horizontal_pull',
    equipment: EquipmentAccess.dumbbells,
    tags: <String>{'general_main', 'bodyweight_support', 'upper_pull'},
    function: 'Ensidig row for ryg og kontrol.',
    alternative: 'Inverted Row',
  ),
  ExerciseKnowledgeItem(
    id: 'EX0141',
    name: 'Cable Pull-Through',
    primaryMuscle: 'Glutes',
    movementPattern: 'hinge',
    equipment: EquipmentAccess.fullGym,
    tags: <String>{'general_support', 'lower'},
    function: 'Rygvenligt hinge-supplement.',
    alternative: 'Hip Hinge Drill',
  ),
  ExerciseKnowledgeItem(
    id: 'RX0008',
    name: 'Knee-to-Wall Ankle Mobilization',
    primaryMuscle: 'Ankles',
    movementPattern: 'mobility',
    equipment: EquipmentAccess.bodyweight,
    tags: <String>{'warmup', 'mobility'},
    function: 'Forbedrer aktiv ankelmobilitet før squat/lunge.',
    alternative: 'Ankle Circles',
  ),
  ExerciseKnowledgeItem(
    id: 'RX0025',
    name: 'Open Book Stretch',
    primaryMuscle: 'Thoracic Spine',
    movementPattern: 'mobility',
    equipment: EquipmentAccess.bodyweight,
    tags: <String>{'warmup', 'mobility'},
    function: 'Mobiliserer thorakal rotation.',
    alternative: 'Thread the Needle',
  ),
  ExerciseKnowledgeItem(
    id: 'RX0021',
    name: 'Lat Stretch on Bench',
    primaryMuscle: 'Lats',
    movementPattern: 'mobility',
    equipment: EquipmentAccess.homeGym,
    tags: <String>{'warmup', 'mobility'},
    function: 'Frigør overhead-position ved skulderarbejde.',
    alternative: 'Prayer Lat Stretch',
  ),
  ExerciseKnowledgeItem(
    id: 'RX0060',
    name: 'Cat-Cow',
    primaryMuscle: 'Spine',
    movementPattern: 'mobility',
    equipment: EquipmentAccess.bodyweight,
    tags: <String>{'warmup', 'mobility'},
    function: 'Blid spinal bevægelse til opvarmning.',
    alternative: 'Lower Trunk Rotation',
  ),
  ExerciseKnowledgeItem(
    id: 'RX0109',
    name: 'Clamshell',
    primaryMuscle: 'Glute Medius',
    movementPattern: 'hip_stability',
    equipment: EquipmentAccess.bodyweight,
    tags: <String>{'mobility_support', 'rehab'},
    function: 'Bygger hoftekontrol og stabilitet.',
    alternative: 'Lateral Band Walk',
  ),
  ExerciseKnowledgeItem(
    id: 'RX0094',
    name: 'Band Row',
    primaryMuscle: 'Back',
    movementPattern: 'horizontal_pull',
    equipment: EquipmentAccess.homeGym,
    tags: <String>{'general_support', 'rehab_friendly', 'upper_pull'},
    function: 'Skånsomt træk med lav indgangsbarriere.',
    alternative: 'TRX Row',
  ),
  ExerciseKnowledgeItem(
    id: 'RX0107',
    name: 'Wall Push-Up',
    primaryMuscle: 'Chest',
    movementPattern: 'horizontal_press',
    equipment: EquipmentAccess.bodyweight,
    tags: <String>{'general_support', 'rehab_friendly', 'upper_press'},
    function: 'Skånsom press-progression.',
    alternative: 'Incline Push-Up',
  ),
  ExerciseKnowledgeItem(
    id: 'RX0119',
    name: 'Standing Hip Abduction',
    primaryMuscle: 'Glute Medius',
    movementPattern: 'abduction',
    equipment: EquipmentAccess.bodyweight,
    tags: <String>{'general_support', 'lower', 'rehab_friendly'},
    function: 'Forbedrer hofteabduktion og bækkenstabilitet.',
    alternative: 'Side-Lying Hip Abduction',
  ),
  ExerciseKnowledgeItem(
    id: 'RX0122',
    name: 'Box Squat to Chair',
    primaryMuscle: 'Legs',
    movementPattern: 'squat',
    equipment: EquipmentAccess.bodyweight,
    tags: <String>{'bodyweight_main', 'general_main', 'lower', 'rehab_friendly'},
    function: 'Kontrolleret squat-progression.',
    alternative: 'Mini Squat',
  ),
  ExerciseKnowledgeItem(
    id: 'RX0052',
    name: 'Child’s Pose',
    primaryMuscle: 'Core',
    movementPattern: 'mobility',
    equipment: EquipmentAccess.bodyweight,
    tags: <String>{'cooldown', 'mobility'},
    function: 'Rolig afsluttende mobilitet og vejrtrækning.',
    alternative: 'Sphinx Stretch',
  ),
];
