platform :ios, '12.0'

flutter_application_path = '../hello'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Host' do
  install_all_flutter_pods flutter_application_path
end

post_install do |installer|
  flutter_post_install(installer)
end
