platform :ios, '9.0'

flutter_application_path = '../hello'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Host' do
  use_modular_headers!
  install_all_flutter_pods flutter_application_path
end
