include: ../analysis_options.yaml

plugins:
  flutter_analyzer_plugin:
    path: ../../dev/flutter_analyzer_plugin
    diagnostics:
      deprecation_syntax: true
      no_sync_async_star: true

analyzer:
  exclude:
    - "test_fixes/**"
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
