/*
 * Copyright 2008, The Android Open Source Project
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

[
    WillBeGarbageCollected,
] interface Touch {
    readonly attribute double           clientX;
    readonly attribute double           clientY;
    readonly attribute double           screenX;
    readonly attribute double           screenY;
    readonly attribute double           pageX;
    readonly attribute double           pageY;
    readonly attribute EventTarget      target;
    readonly attribute unsigned long    identifier;
    readonly attribute double           radiusX;
    readonly attribute double           radiusY;
    readonly attribute float            force;
    [MeasureAs=PrefixedTouchRadiusX] readonly attribute double webkitRadiusX;
    [MeasureAs=PrefixedTouchRadiusY] readonly attribute double webkitRadiusY;
    [MeasureAs=PrefixedTouchRotationAngle] readonly attribute float webkitRotationAngle;
    [MeasureAs=PrefixedTouchForce] readonly attribute float webkitForce;
};
