platform :ios, '12.0'

flutter_application_path = 'flutterapp/'

load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'ios_add2app' do
  install_all_flutter_pods(flutter_application_path)
  pod 'EarlGreyApp'
end

target 'ios_add2appTests' do
  install_flutter_engine_pod
  pod 'EarlGreyTest'
end

post_install do |installer|
  flutter_post_install(installer)
end
