// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#import <Foundation/Foundation.h>
#import <OCMock/OCMock.h>
#import <UIKit/UIKit.h>
#import <XCTest/XCTest.h>
#include <objc/NSObject.h>

#import "flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine+Test.h"
#import "flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine_Internal.h"
#import "flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegate_internal.h"
#import "flutter/shell/platform/darwin/ios/framework/Source/FlutterRestorationPlugin.h"
#import "flutter/shell/platform/darwin/ios/framework/Source/FlutterSceneLifeCycle+Test.h"
#import "flutter/shell/platform/darwin/ios/framework/Source/FlutterSceneLifeCycle_Internal.h"
#import "flutter/shell/platform/darwin/ios/framework/Source/FlutterSharedApplication.h"

FLUTTER_ASSERT_ARC

// This class is meant to mimic the SceneDelegate class generated by SwiftUI that does not conform
// FlutterSceneLifeCycleProvider but actually does.
@interface FlutterSwiftUIAppSceneDelegate : NSObject
@property(nonatomic, readonly) FlutterPluginSceneLifeCycleDelegate* sceneLifeCycleDelegate;
@end

@implementation FlutterSwiftUIAppSceneDelegate

@synthesize sceneLifeCycleDelegate = _sceneLifeCycleDelegate;

- (instancetype)init {
  if (self = [super init]) {
    _sceneLifeCycleDelegate = [[FlutterPluginSceneLifeCycleDelegate alloc] init];
  }
  return self;
}
@end

// This class is not referenced in test because it's a test itself. The implementation
// verifies that sceneLifeCycleDelegate is a readonly property.
@interface TestSceneLifecycleProvider : NSObject <FlutterSceneLifeCycleProvider>
@end
@implementation TestSceneLifecycleProvider
- (FlutterPluginSceneLifeCycleDelegate*)sceneLifeCycleDelegate {
  return [[FlutterPluginSceneLifeCycleDelegate alloc] init];
}
@end

@interface FlutterSceneLifecycleTest : XCTestCase
@end

@implementation FlutterSceneLifecycleTest
- (void)setUp {
  [super setUp];
  [FlutterPluginSceneLifeCycleDelegate resetSceneWillConnectFallbackCalledForTesting];
  [FlutterPluginSceneLifeCycleDelegate resetEnginesForSingleSceneForTesting];
}

#pragma mark - Single-Scene Engine Registration and Discovery

- (void)testSingleSceneEngineRegistrationAndDiscovery {
  id mockApplication = OCMClassMock([UIApplication class]);
  OCMStub([mockApplication sharedApplication]).andReturn(mockApplication);
  OCMStub([mockApplication supportsMultipleScenes]).andReturn(NO);

  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mockEngine = OCMClassMock([FlutterEngine class]);
  [FlutterPluginSceneLifeCycleDelegate registerEngineForSingleScene:mockEngine];

  id mockScene = OCMClassMock([UIScene class]);
  NSArray<FlutterEngine*>* engines = [delegate searchFlutterEnginesWithScene:mockScene];
  XCTAssertEqual(engines.count, 1.0);
  XCTAssertTrue([engines containsObject:mockEngine]);

  [mockApplication stopMocking];
}

- (void)testSingleSceneMultipleEnginesRegistration {
  id mockApplication = OCMClassMock([UIApplication class]);
  OCMStub([mockApplication sharedApplication]).andReturn(mockApplication);
  OCMStub([mockApplication supportsMultipleScenes]).andReturn(NO);

  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mockEngine1 = OCMClassMock([FlutterEngine class]);
  id mockEngine2 = OCMClassMock([FlutterEngine class]);
  [FlutterPluginSceneLifeCycleDelegate registerEngineForSingleScene:mockEngine1];
  [FlutterPluginSceneLifeCycleDelegate registerEngineForSingleScene:mockEngine2];

  id mockScene = OCMClassMock([UIScene class]);
  NSArray<FlutterEngine*>* engines = [delegate searchFlutterEnginesWithScene:mockScene];
  XCTAssertEqual(engines.count, 2.0);
  XCTAssertTrue([engines containsObject:mockEngine1]);
  XCTAssertTrue([engines containsObject:mockEngine2]);

  [mockApplication stopMocking];
}

- (void)testSingleSceneDeallocatedEnginePruned {
  id mockApplication = OCMClassMock([UIApplication class]);
  OCMStub([mockApplication sharedApplication]).andReturn(mockApplication);
  OCMStub([mockApplication supportsMultipleScenes]).andReturn(NO);

  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  @autoreleasepool {
    id mockEngine = OCMClassMock([FlutterEngine class]);
    [FlutterPluginSceneLifeCycleDelegate registerEngineForSingleScene:mockEngine];
    id mockScene = OCMClassMock([UIScene class]);
    XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);
  }

  id mockScene = OCMClassMock([UIScene class]);
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 0.0);

  [mockApplication stopMocking];
}

#pragma mark - Multi-Scene View Controller Hierarchy Searching

- (void)testSearchFlutterViewControllersWithSceneRootViewController {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mockScene = OCMClassMock([UIWindowScene class]);
  id mockWindow = OCMClassMock([UIWindow class]);
  id mockViewController = OCMClassMock([FlutterViewController class]);

  OCMStub([mockScene windows]).andReturn(@[ mockWindow ]);
  OCMStub([mockWindow rootViewController]).andReturn(mockViewController);

  NSArray<FlutterViewController*>* vcs =
      [delegate searchFlutterViewControllersWithScene:mockScene];
  XCTAssertEqual(vcs.count, 1.0);
  XCTAssertEqualObjects(vcs.firstObject, mockViewController);
}

- (void)testSearchFlutterViewControllersWithSceneChildViewControllers {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mockScene = OCMClassMock([UIWindowScene class]);
  id mockWindow = OCMClassMock([UIWindow class]);
  id rootVC = OCMClassMock([UIViewController class]);
  id childNormalVC = OCMClassMock([UIViewController class]);
  id childFlutterVC = OCMClassMock([FlutterViewController class]);

  OCMStub([mockScene windows]).andReturn(@[ mockWindow ]);
  OCMStub([mockWindow rootViewController]).andReturn(rootVC);
  OCMStub([rootVC childViewControllers]).andReturn((@[ childNormalVC, childFlutterVC ]));
  OCMStub([childNormalVC childViewControllers]).andReturn(@[]);
  OCMStub([childFlutterVC childViewControllers]).andReturn(@[]);

  NSArray<FlutterViewController*>* vcs =
      [delegate searchFlutterViewControllersWithScene:mockScene];
  XCTAssertEqual(vcs.count, 1.0);
  XCTAssertEqualObjects(vcs.firstObject, childFlutterVC);
}

- (void)testSearchFlutterViewControllersWithScenePresentedViewController {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mockScene = OCMClassMock([UIWindowScene class]);
  id mockWindow = OCMClassMock([UIWindow class]);
  id rootVC = OCMClassMock([UIViewController class]);
  id presentedFlutterVC = OCMClassMock([FlutterViewController class]);

  OCMStub([mockScene windows]).andReturn(@[ mockWindow ]);
  OCMStub([mockWindow rootViewController]).andReturn(rootVC);
  OCMStub([rootVC childViewControllers]).andReturn(@[]);
  OCMStub([rootVC presentedViewController]).andReturn(presentedFlutterVC);
  OCMStub([presentedFlutterVC childViewControllers]).andReturn(@[]);

  NSArray<FlutterViewController*>* vcs =
      [delegate searchFlutterViewControllersWithScene:mockScene];
  XCTAssertEqual(vcs.count, 1.0);
  XCTAssertEqualObjects(vcs.firstObject, presentedFlutterVC);
}

- (void)testSearchFlutterViewControllersWithSceneMultipleWindows {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mockScene = OCMClassMock([UIWindowScene class]);
  id mockWindow1 = OCMClassMock([UIWindow class]);
  id mockWindow2 = OCMClassMock([UIWindow class]);
  id mockFlutterVC1 = OCMClassMock([FlutterViewController class]);
  id mockFlutterVC2 = OCMClassMock([FlutterViewController class]);

  OCMStub([mockScene windows]).andReturn((@[ mockWindow1, mockWindow2 ]));
  OCMStub([mockWindow1 rootViewController]).andReturn(mockFlutterVC1);
  OCMStub([mockWindow2 rootViewController]).andReturn(mockFlutterVC2);

  NSArray<FlutterViewController*>* vcs =
      [delegate searchFlutterViewControllersWithScene:mockScene];
  XCTAssertEqual(vcs.count, 2.0);
  XCTAssertTrue([vcs containsObject:mockFlutterVC1]);
  XCTAssertTrue([vcs containsObject:mockFlutterVC2]);
}

- (void)testSearchFlutterViewControllersWithSceneCycleProtection {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mockScene = OCMClassMock([UIWindowScene class]);
  id mockWindow = OCMClassMock([UIWindow class]);
  id vc1 = OCMClassMock([UIViewController class]);
  id vc2 = OCMClassMock([UIViewController class]);
  id flutterVC = OCMClassMock([FlutterViewController class]);

  OCMStub([mockScene windows]).andReturn(@[ mockWindow ]);
  OCMStub([mockWindow rootViewController]).andReturn(vc1);
  // Introduce cycle between vc1 and vc2
  OCMStub([vc1 childViewControllers]).andReturn((@[ vc2, flutterVC ]));
  OCMStub([vc2 childViewControllers]).andReturn(@[ vc1 ]);
  OCMStub([flutterVC childViewControllers]).andReturn(@[]);

  NSArray<FlutterViewController*>* vcs =
      [delegate searchFlutterViewControllersWithScene:mockScene];
  XCTAssertEqual(vcs.count, 1.0);
  XCTAssertEqualObjects(vcs.firstObject, flutterVC);
}

- (void)testSearchFlutterViewControllersWithNonWindowScene {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mockScene = OCMClassMock([UIScene class]);
  NSArray<FlutterViewController*>* vcs =
      [delegate searchFlutterViewControllersWithScene:mockScene];
  XCTAssertEqual(vcs.count, 0.0);
}

#pragma mark - Multi-Scene Engine Registration and Searching

- (void)testRegisterSceneLifeCycleWithFlutterEngineSuccess {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mockScene = OCMClassMock([UIScene class]);
  id mockEngine = OCMClassMock([FlutterEngine class]);

  BOOL result = [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertTrue(result);
  NSPointerArray* engines = [delegate.developerManagedEngines objectForKey:mockScene];
  XCTAssertEqual(engines.allObjects.count, 1.0);
  XCTAssertTrue([engines.allObjects containsObject:mockEngine]);
}

- (void)testRegisterSceneLifeCycleWithFlutterEngineDuplicateReturnsNO {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mockScene = OCMClassMock([UIScene class]);
  id mockEngine = OCMClassMock([FlutterEngine class]);

  XCTAssertTrue([delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene]);
  XCTAssertFalse([delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene]);
  NSPointerArray* engines = [delegate.developerManagedEngines objectForKey:mockScene];
  XCTAssertEqual(engines.allObjects.count, 1.0);
}

- (void)testRegisterMultipleEnginesForSameScene {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mockScene = OCMClassMock([UIScene class]);
  id mockEngine1 = OCMClassMock([FlutterEngine class]);
  id mockEngine2 = OCMClassMock([FlutterEngine class]);

  XCTAssertTrue([delegate registerSceneLifeCycleWithFlutterEngine:mockEngine1 scene:mockScene]);
  XCTAssertTrue([delegate registerSceneLifeCycleWithFlutterEngine:mockEngine2 scene:mockScene]);
  NSPointerArray* engines = [delegate.developerManagedEngines objectForKey:mockScene];
  XCTAssertEqual(engines.allObjects.count, 2.0);
  XCTAssertTrue([engines.allObjects containsObject:mockEngine1]);
  XCTAssertTrue([engines.allObjects containsObject:mockEngine2]);
}

- (void)testUnregisterSceneLifeCycleWithFlutterEngineSuccess {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mockScene = OCMClassMock([UIScene class]);
  id mockEngine = OCMClassMock([FlutterEngine class]);

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  BOOL unregistered =
      [delegate unregisterSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertTrue(unregistered);

  NSPointerArray* engines = [delegate.developerManagedEngines objectForKey:mockScene];
  XCTAssertEqual(engines.allObjects.count, 0.0);
}

- (void)testUnregisterSceneLifeCycleWithUnregisteredEngineReturnsNO {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mockScene = OCMClassMock([UIScene class]);
  id mockEngine = OCMClassMock([FlutterEngine class]);

  BOOL unregistered =
      [delegate unregisterSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertFalse(unregistered);
}

- (void)testUnregisterSceneLifeCycleFromDifferentSceneReturnsNO {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mockScene1 = OCMClassMock([UIScene class]);
  id mockScene2 = OCMClassMock([UIScene class]);
  id mockEngine = OCMClassMock([FlutterEngine class]);

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene1];

  BOOL unregistered =
      [delegate unregisterSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene2];
  XCTAssertFalse(unregistered);

  NSPointerArray* engines1 = [delegate.developerManagedEngines objectForKey:mockScene1];
  XCTAssertEqual(engines1.allObjects.count, 1.0);
}

- (void)testSearchFlutterEnginesMultiSceneCombinesViewControllersAndDeveloperEngines {
  id mockApplication = OCMClassMock([UIApplication class]);
  OCMStub([mockApplication sharedApplication]).andReturn(mockApplication);
  OCMStub([mockApplication supportsMultipleScenes]).andReturn(YES);

  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mockScene = OCMClassMock([UIWindowScene class]);
  id mockWindow = OCMClassMock([UIWindow class]);
  id mockFlutterVC = OCMClassMock([FlutterViewController class]);
  id vcEngine = OCMClassMock([FlutterEngine class]);
  id devEngine = OCMClassMock([FlutterEngine class]);

  OCMStub([mockScene windows]).andReturn(@[ mockWindow ]);
  OCMStub([mockWindow rootViewController]).andReturn(mockFlutterVC);
  OCMStub([mockFlutterVC engine]).andReturn(vcEngine);

  [delegate registerSceneLifeCycleWithFlutterEngine:devEngine scene:mockScene];

  NSArray<FlutterEngine*>* engines = [delegate searchFlutterEnginesWithScene:mockScene];
  XCTAssertEqual(engines.count, 2.0);
  XCTAssertTrue([engines containsObject:vcEngine]);
  XCTAssertTrue([engines containsObject:devEngine]);

  [mockApplication stopMocking];
}

- (void)testSearchFlutterEnginesMultiSceneDeduplicatesViewControllerAndDeveloperEngines {
  id mockApplication = OCMClassMock([UIApplication class]);
  OCMStub([mockApplication sharedApplication]).andReturn(mockApplication);
  OCMStub([mockApplication supportsMultipleScenes]).andReturn(YES);

  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mockScene = OCMClassMock([UIWindowScene class]);
  id mockWindow = OCMClassMock([UIWindow class]);
  id mockFlutterVC = OCMClassMock([FlutterViewController class]);
  id sharedEngine = OCMClassMock([FlutterEngine class]);

  OCMStub([mockScene windows]).andReturn(@[ mockWindow ]);
  OCMStub([mockWindow rootViewController]).andReturn(mockFlutterVC);
  OCMStub([mockFlutterVC engine]).andReturn(sharedEngine);

  [delegate registerSceneLifeCycleWithFlutterEngine:sharedEngine scene:mockScene];

  NSArray<FlutterEngine*>* engines = [delegate searchFlutterEnginesWithScene:mockScene];
  XCTAssertEqual(engines.count, 1.0);
  XCTAssertEqualObjects(engines.firstObject, sharedEngine);

  [mockApplication stopMocking];
}

- (void)testSearchFlutterEnginesMultiSceneFiltersByScene {
  id mockApplication = OCMClassMock([UIApplication class]);
  OCMStub([mockApplication sharedApplication]).andReturn(mockApplication);
  OCMStub([mockApplication supportsMultipleScenes]).andReturn(YES);

  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mockScene1 = OCMClassMock([UIScene class]);
  id mockScene2 = OCMClassMock([UIScene class]);
  id mockEngine1 = OCMClassMock([FlutterEngine class]);
  id mockEngine2 = OCMClassMock([FlutterEngine class]);

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine1 scene:mockScene1];
  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine2 scene:mockScene2];

  NSArray<FlutterEngine*>* engines1 = [delegate searchFlutterEnginesWithScene:mockScene1];
  XCTAssertEqual(engines1.count, 1.0);
  XCTAssertTrue([engines1 containsObject:mockEngine1]);
  XCTAssertFalse([engines1 containsObject:mockEngine2]);

  NSArray<FlutterEngine*>* engines2 = [delegate searchFlutterEnginesWithScene:mockScene2];
  XCTAssertEqual(engines2.count, 1.0);
  XCTAssertTrue([engines2 containsObject:mockEngine2]);
  XCTAssertFalse([engines2 containsObject:mockEngine1]);

  [mockApplication stopMocking];
}

#pragma mark - Connection Window & connectEngineIfNeeded

- (void)testSceneWillConnectSetsConnectingScenesAndConnectsAttachedEngines {
  id mockApplication = OCMClassMock([UIApplication class]);
  OCMStub([mockApplication sharedApplication]).andReturn(mockApplication);
  OCMStub([mockApplication supportsMultipleScenes]).andReturn(YES);

  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];
  FlutterPluginSceneLifeCycleDelegate* mockDelegate = OCMPartialMock(delegate);

  id mockScene = OCMClassMock([UIWindowScene class]);
  id mockWindow = OCMClassMock([UIWindow class]);
  id mockFlutterVC = OCMClassMock([FlutterViewController class]);
  id mockEngine = OCMClassMock([FlutterEngine class]);

  OCMStub([mockScene windows]).andReturn(@[ mockWindow ]);
  OCMStub([mockWindow rootViewController]).andReturn(mockFlutterVC);
  OCMStub([mockFlutterVC engine]).andReturn(mockEngine);

  id session = OCMClassMock([UISceneSession class]);
  id options = OCMClassMock([UISceneConnectionOptions class]);
  OCMStub([mockScene session]).andReturn(session);

  [mockDelegate scene:mockScene willConnectToSession:session options:options];

  XCTAssertEqualObjects([delegate.connectingScenes objectForKey:mockScene], options);
  OCMVerify(times(1), [mockDelegate scene:mockScene
                          willConnectToSession:session
                                 flutterEngine:mockEngine
                                       options:options]);

  [mockApplication stopMocking];
}

- (void)testEngineAttachedDuringConnectionWindowReceivesConnectionEventOnForeground {
  id mockApplication = OCMClassMock([UIApplication class]);
  OCMStub([mockApplication sharedApplication]).andReturn(mockApplication);
  OCMStub([mockApplication supportsMultipleScenes]).andReturn(YES);

  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];
  FlutterPluginSceneLifeCycleDelegate* mockDelegate = OCMPartialMock(delegate);

  id mockScene = OCMClassMock([UIWindowScene class]);
  id session = OCMClassMock([UISceneSession class]);
  id options = OCMClassMock([UISceneConnectionOptions class]);
  OCMStub([mockScene session]).andReturn(session);
  OCMStub([mockScene windows]).andReturn(@[]);

  // Start scene connection with no engines attached initially
  [mockDelegate scene:mockScene willConnectToSession:session options:options];

  // Engine is registered during the connection window (e.g., during viewDidLoad)
  id mockEngine = OCMClassMock([FlutterEngine class]);
  id mockLifecycleDelegate = OCMClassMock([FlutterEnginePluginSceneLifeCycleDelegate class]);
  OCMStub([mockEngine sceneLifeCycleDelegate]).andReturn(mockLifecycleDelegate);
  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];

  // Foreground event triggers connectEngineIfNeeded:
  [mockDelegate sceneWillEnterForeground:mockScene];

  OCMVerify(times(1), [mockDelegate scene:mockScene
                          willConnectToSession:session
                                 flutterEngine:mockEngine
                                       options:options]);

  // Subsequent foreground event should not duplicate connection event
  [mockDelegate sceneWillEnterForeground:mockScene];
  OCMVerify(times(1), [mockDelegate scene:mockScene
                          willConnectToSession:session
                                 flutterEngine:mockEngine
                                       options:options]);

  [mockApplication stopMocking];
}

- (void)testEngineAttachedDuringConnectionWindowReceivesConnectionEventOnBackground {
  id mockApplication = OCMClassMock([UIApplication class]);
  OCMStub([mockApplication sharedApplication]).andReturn(mockApplication);
  OCMStub([mockApplication supportsMultipleScenes]).andReturn(YES);

  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];
  FlutterPluginSceneLifeCycleDelegate* mockDelegate = OCMPartialMock(delegate);

  id mockScene = OCMClassMock([UIWindowScene class]);
  id session = OCMClassMock([UISceneSession class]);
  id options = OCMClassMock([UISceneConnectionOptions class]);
  OCMStub([mockScene session]).andReturn(session);
  OCMStub([mockScene windows]).andReturn(@[]);

  [mockDelegate scene:mockScene willConnectToSession:session options:options];

  id mockEngine = OCMClassMock([FlutterEngine class]);
  id mockLifecycleDelegate = OCMClassMock([FlutterEnginePluginSceneLifeCycleDelegate class]);
  OCMStub([mockEngine sceneLifeCycleDelegate]).andReturn(mockLifecycleDelegate);
  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];

  [mockDelegate sceneDidEnterBackground:mockScene];

  OCMVerify(times(1), [mockDelegate scene:mockScene
                          willConnectToSession:session
                                 flutterEngine:mockEngine
                                       options:options]);

  [mockApplication stopMocking];
}

- (void)testConnectEngineIfNeededDoesNothingWhenNotConnecting {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];
  FlutterPluginSceneLifeCycleDelegate* mockDelegate = OCMPartialMock(delegate);

  id mockScene = OCMClassMock([UIWindowScene class]);
  id mockEngine = OCMClassMock([FlutterEngine class]);

  [mockDelegate connectEngineIfNeeded:mockEngine scene:mockScene];

  OCMVerify(times(0), [mockDelegate scene:mockScene
                          willConnectToSession:[OCMArg any]
                                 flutterEngine:mockEngine
                                       options:[OCMArg any]]);
}

- (void)testSceneWillConnectToSessionOptionsHandledByScenePlugin {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate =
      (FlutterEnginePluginSceneLifeCycleDelegate*)mocks[@"mockLifecycleDelegate"];
  OCMStub([mockLifecycleDelegate scene:[OCMArg any]
                  willConnectToSession:[OCMArg any]
                               options:[OCMArg any]])
      .andReturn(YES);
  id mockAppLifecycleDelegate = mocks[@"mockAppLifecycleDelegate"];
  OCMStub([mockAppLifecycleDelegate sceneWillConnectFallback:[OCMArg any]]).andReturn(YES);

  id session = mocks[@"mockSession"];
  id options = OCMClassMock([UISceneConnectionOptions class]);

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);

  [delegate scene:mockScene willConnectToSession:session options:options];
  OCMVerify(times(1), [mockLifecycleDelegate scene:mockScene
                              willConnectToSession:session
                                           options:options]);
  OCMVerify(times(0), [mockAppLifecycleDelegate sceneWillConnectFallback:options]);
  OCMVerify(times(0), [mockEngine sendDeepLinkToFramework:[OCMArg any]
                                        completionHandler:[OCMArg any]]);
}

- (void)testSceneWillConnectToSessionOptionsHandledByApplicationPlugin {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate =
      (FlutterEnginePluginSceneLifeCycleDelegate*)mocks[@"mockLifecycleDelegate"];
  OCMStub([mockLifecycleDelegate scene:[OCMArg any]
                  willConnectToSession:[OCMArg any]
                               options:[OCMArg any]])
      .andReturn(NO);
  id mockAppLifecycleDelegate = mocks[@"mockAppLifecycleDelegate"];
  OCMStub([mockAppLifecycleDelegate sceneWillConnectFallback:[OCMArg any]]).andReturn(YES);

  id session = mocks[@"mockSession"];
  id options = OCMClassMock([UISceneConnectionOptions class]);

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);

  [delegate scene:mockScene willConnectToSession:session options:options];
  OCMVerify(times(1), [mockLifecycleDelegate scene:mockScene
                              willConnectToSession:session
                                           options:options]);
  OCMVerify(times(1), [mockAppLifecycleDelegate sceneWillConnectFallback:options]);
  OCMVerify(times(0), [mockEngine sendDeepLinkToFramework:[OCMArg any]
                                        completionHandler:[OCMArg any]]);
}

- (void)testSceneWillConnectToSessionOptionsHandledByApplicationPluginMultipleEngines {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate =
      (FlutterEnginePluginSceneLifeCycleDelegate*)mocks[@"mockLifecycleDelegate"];
  OCMStub([mockLifecycleDelegate scene:[OCMArg any]
                  willConnectToSession:[OCMArg any]
                               options:[OCMArg any]])
      .andReturn(NO);

  id mocks2 = [self mocksForEvents];
  id mockEngine2 = mocks2[@"mockEngine"];
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate2 =
      (FlutterEnginePluginSceneLifeCycleDelegate*)mocks2[@"mockLifecycleDelegate"];
  OCMStub([mockLifecycleDelegate2 scene:[OCMArg any]
                   willConnectToSession:[OCMArg any]
                                options:[OCMArg any]])
      .andReturn(NO);

  id mockAppLifecycleDelegate = mocks2[@"mockAppLifecycleDelegate"];
  OCMStub([mockAppLifecycleDelegate sceneWillConnectFallback:[OCMArg any]]).andReturn(YES);
  id session = mocks[@"mockSession"];
  id options = OCMClassMock([UISceneConnectionOptions class]);

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine2 scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 2.0);

  [delegate scene:mockScene willConnectToSession:session options:options];
  OCMVerify(times(1), [mockLifecycleDelegate scene:mockScene
                              willConnectToSession:session
                                           options:options]);
  OCMVerify(times(1), [mockLifecycleDelegate2 scene:mockScene
                               willConnectToSession:session
                                            options:nil]);
  OCMVerify(times(1), [mockAppLifecycleDelegate sceneWillConnectFallback:options]);
  OCMVerify(times(0), [mockEngine sendDeepLinkToFramework:[OCMArg any]
                                        completionHandler:[OCMArg any]]);
}

- (void)testSceneWillConnectToSessionOptionsHandledByUniversalLinks {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate =
      (FlutterEnginePluginSceneLifeCycleDelegate*)mocks[@"mockLifecycleDelegate"];
  OCMStub([mockLifecycleDelegate scene:[OCMArg any]
                  willConnectToSession:[OCMArg any]
                               options:[OCMArg any]])
      .andReturn(NO);

  id session = mocks[@"mockSession"];
  id options = OCMClassMock([UISceneConnectionOptions class]);
  id userActivity = OCMClassMock([NSUserActivity class]);
  id flutterApp = OCMClassMock([FlutterSharedApplication class]);
  NSURL* url = [NSURL URLWithString:@"example.com"];
  OCMStub([userActivity webpageURL]).andReturn(url);
  NSSet<NSUserActivity*>* userActivities = [NSSet setWithObjects:userActivity, nil];
  OCMStub([options userActivities]).andReturn(userActivities);
  OCMStub([flutterApp isFlutterDeepLinkingEnabled]).andReturn(YES);

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);

  [delegate scene:mockScene willConnectToSession:session options:options];
  OCMVerify(times(1), [mockEngine sendDeepLinkToFramework:url completionHandler:[OCMArg any]]);
}

- (void)testSceneWillConnectToSessionOptionsHandledByDeepLinks {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate =
      (FlutterEnginePluginSceneLifeCycleDelegate*)mocks[@"mockLifecycleDelegate"];
  OCMStub([mockLifecycleDelegate scene:[OCMArg any]
                  willConnectToSession:[OCMArg any]
                               options:[OCMArg any]])
      .andReturn(NO);

  id session = mocks[@"mockSession"];
  id options = OCMClassMock([UISceneConnectionOptions class]);
  id flutterApp = OCMClassMock([FlutterSharedApplication class]);
  NSURL* url = [NSURL URLWithString:@"example.com"];
  OCMStub([flutterApp isFlutterDeepLinkingEnabled]).andReturn(YES);
  id urlContext = OCMClassMock([UIOpenURLContext class]);
  OCMStub([urlContext URL]).andReturn(url);
  NSSet<UIOpenURLContext*>* urlContexts = [NSSet setWithObjects:urlContext, nil];
  OCMStub([options URLContexts]).andReturn(urlContexts);

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);

  [delegate scene:mockScene willConnectToSession:session options:options];
  OCMVerify(times(1), [mockEngine sendDeepLinkToFramework:url completionHandler:[OCMArg any]]);
}

- (void)testSceneWillConnectToSessionOptionsHandledByNoPlugin {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate =
      (FlutterEnginePluginSceneLifeCycleDelegate*)mocks[@"mockLifecycleDelegate"];
  OCMStub([mockLifecycleDelegate scene:[OCMArg any]
                  willConnectToSession:[OCMArg any]
                               options:[OCMArg any]])
      .andReturn(NO);

  id session = mocks[@"mockSession"];
  id options = OCMClassMock([UISceneConnectionOptions class]);
  id userActivity = OCMClassMock([NSUserActivity class]);
  id flutterApp = OCMClassMock([FlutterSharedApplication class]);
  NSURL* url = [NSURL URLWithString:@"example.com"];
  OCMStub([userActivity webpageURL]).andReturn(url);
  NSSet<NSUserActivity*>* userActivities = [NSSet setWithObjects:userActivity, nil];
  OCMStub([options userActivities]).andReturn(userActivities);
  OCMStub([flutterApp isFlutterDeepLinkingEnabled]).andReturn(NO);

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);

  [delegate scene:mockScene willConnectToSession:session options:options];
  OCMVerify(times(0), [mockEngine sendDeepLinkToFramework:url completionHandler:[OCMArg any]]);
}

- (void)testSceneWillConnectToSessionDiscoversEngineFromRootViewController {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];
  FlutterPluginSceneLifeCycleDelegate* mockDelegate = OCMPartialMock(delegate);

  id mockApplication = OCMClassMock([UIApplication class]);
  OCMStub([mockApplication sharedApplication]).andReturn(mockApplication);
  OCMStub([mockApplication supportsMultipleScenes]).andReturn(YES);

  id mockScene = OCMClassMock([UIWindowScene class]);
  id mockWindow = OCMClassMock([UIWindow class]);
  id mockViewController = OCMClassMock([FlutterViewController class]);
  id mockEngine = OCMClassMock([FlutterEngine class]);

  OCMStub([mockScene windows]).andReturn(@[ mockWindow ]);
  OCMStub([mockWindow rootViewController]).andReturn(mockViewController);
  OCMStub([mockViewController engine]).andReturn(mockEngine);

  id session = OCMClassMock([UISceneSession class]);
  id options = OCMClassMock([UISceneConnectionOptions class]);
  OCMStub([mockScene session]).andReturn(session);

  [mockDelegate scene:mockScene willConnectToSession:session options:options];

  OCMVerify(times(1), [mockDelegate scene:mockScene
                          willConnectToSession:session
                                 flutterEngine:mockEngine
                                       options:options]);

  [mockApplication stopMocking];
}

- (void)testSceneWillConnectToSessionDoesNotDuplicateConnectionEventOnSubsequentLifecycleEvent {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];
  FlutterPluginSceneLifeCycleDelegate* mockDelegate = OCMPartialMock(delegate);

  id mockApplication = OCMClassMock([UIApplication class]);
  OCMStub([mockApplication sharedApplication]).andReturn(mockApplication);
  OCMStub([mockApplication supportsMultipleScenes]).andReturn(YES);

  id mockScene = OCMClassMock([UIWindowScene class]);
  id mockWindow = OCMClassMock([UIWindow class]);
  id mockViewController = OCMClassMock([FlutterViewController class]);
  id mockEngine = OCMClassMock([FlutterEngine class]);

  OCMStub([mockScene windows]).andReturn(@[ mockWindow ]);
  OCMStub([mockWindow rootViewController]).andReturn(mockViewController);
  OCMStub([mockViewController engine]).andReturn(mockEngine);

  id session = OCMClassMock([UISceneSession class]);
  id options = OCMClassMock([UISceneConnectionOptions class]);
  OCMStub([mockScene session]).andReturn(session);

  [mockDelegate scene:mockScene willConnectToSession:session options:options];
  [mockDelegate sceneWillEnterForeground:mockScene];

  OCMVerify(times(1), [mockDelegate scene:mockScene
                          willConnectToSession:session
                                 flutterEngine:mockEngine
                                       options:options]);

  [mockApplication stopMocking];
}

- (void)testSceneDidDisconnect {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  id mockLifecycleDelegate = mocks[@"mockLifecycleDelegate"];

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);

  [delegate sceneDidDisconnect:mockScene];
  OCMVerify(times(1), [mockLifecycleDelegate sceneDidDisconnect:mockScene]);
}

- (void)testSceneWillEnterForeground {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  id mockLifecycleDelegate = mocks[@"mockLifecycleDelegate"];
  id mockAppLifecycleDelegate = mocks[@"mockAppLifecycleDelegate"];

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);

  [delegate sceneWillEnterForeground:mockScene];
  OCMVerify(times(1), [mockLifecycleDelegate sceneWillEnterForeground:mockScene]);
  OCMVerify(times(1), [mockAppLifecycleDelegate sceneWillEnterForegroundFallback]);
}

- (void)testSceneDidBecomeActive {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  id mockLifecycleDelegate = mocks[@"mockLifecycleDelegate"];
  id mockAppLifecycleDelegate = mocks[@"mockAppLifecycleDelegate"];

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);

  [delegate sceneDidBecomeActive:mockScene];
  OCMVerify(times(1), [mockLifecycleDelegate sceneDidBecomeActive:mockScene]);
  OCMVerify(times(1), [mockAppLifecycleDelegate sceneDidBecomeActiveFallback]);
}

- (void)testSceneWillResignActive {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  id mockLifecycleDelegate = mocks[@"mockLifecycleDelegate"];
  id mockAppLifecycleDelegate = mocks[@"mockAppLifecycleDelegate"];

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);

  [delegate sceneWillResignActive:mockScene];
  OCMVerify(times(1), [mockLifecycleDelegate sceneWillResignActive:mockScene]);
  OCMVerify(times(1), [mockAppLifecycleDelegate sceneWillResignActiveFallback]);
}

- (void)testSceneDidEnterBackground {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  id mockLifecycleDelegate = mocks[@"mockLifecycleDelegate"];
  id mockAppLifecycleDelegate = mocks[@"mockAppLifecycleDelegate"];

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);

  [delegate sceneDidEnterBackground:mockScene];
  OCMVerify(times(1), [mockLifecycleDelegate sceneDidEnterBackground:mockScene]);
  OCMVerify(times(1), [mockAppLifecycleDelegate sceneDidEnterBackgroundFallback]);
}

- (void)testSceneOpenURLContextsHandledByScenePlugin {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate =
      (FlutterEnginePluginSceneLifeCycleDelegate*)mocks[@"mockLifecycleDelegate"];
  id mockAppLifecycleDelegate = mocks[@"mockAppLifecycleDelegate"];
  OCMStub([mockLifecycleDelegate scene:[OCMArg any] openURLContexts:[OCMArg any]]).andReturn(YES);
  OCMStub([mockAppLifecycleDelegate sceneFallbackOpenURLContexts:[OCMArg any]]).andReturn(YES);

  id urlContext = OCMClassMock([UIOpenURLContext class]);
  NSSet<UIOpenURLContext*>* urlContexts = [NSSet setWithObjects:urlContext, nil];

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);

  [delegate scene:mockScene openURLContexts:urlContexts];
  OCMVerify(times(1), [mockLifecycleDelegate scene:mockScene openURLContexts:urlContexts]);
  OCMVerify(times(0), [mockAppLifecycleDelegate sceneFallbackOpenURLContexts:urlContexts]);
}

- (void)testSceneOpenURLContextsHandledByApplicationPlugin {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate =
      (FlutterEnginePluginSceneLifeCycleDelegate*)mocks[@"mockLifecycleDelegate"];
  id mockAppLifecycleDelegate = mocks[@"mockAppLifecycleDelegate"];
  OCMStub([mockLifecycleDelegate scene:[OCMArg any] openURLContexts:[OCMArg any]]).andReturn(NO);
  OCMStub([mockAppLifecycleDelegate sceneFallbackOpenURLContexts:[OCMArg any]]).andReturn(YES);

  id urlContext = OCMClassMock([UIOpenURLContext class]);
  NSSet<UIOpenURLContext*>* urlContexts = [NSSet setWithObjects:urlContext, nil];

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);

  [delegate scene:mockScene openURLContexts:urlContexts];
  OCMVerify(times(1), [mockLifecycleDelegate scene:mockScene openURLContexts:urlContexts]);
  OCMVerify(times(1), [mockAppLifecycleDelegate sceneFallbackOpenURLContexts:urlContexts]);
}

- (void)testSceneOpenURLContextsHandledByDeeplink {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate =
      (FlutterEnginePluginSceneLifeCycleDelegate*)mocks[@"mockLifecycleDelegate"];
  id mockAppLifecycleDelegate = mocks[@"mockAppLifecycleDelegate"];
  OCMStub([mockLifecycleDelegate scene:[OCMArg any] openURLContexts:[OCMArg any]]).andReturn(NO);
  OCMStub([mockAppLifecycleDelegate sceneFallbackOpenURLContexts:[OCMArg any]]).andReturn(NO);
  id flutterApp = OCMClassMock([FlutterSharedApplication class]);
  OCMStub([flutterApp isFlutterDeepLinkingEnabled]).andReturn(YES);

  NSURL* url = [NSURL URLWithString:@"example.com"];
  id urlContext = OCMClassMock([UIOpenURLContext class]);
  OCMStub([urlContext URL]).andReturn(url);
  NSSet<UIOpenURLContext*>* urlContexts = [NSSet setWithObjects:urlContext, nil];

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);

  [delegate scene:mockScene openURLContexts:urlContexts];
  OCMVerify(times(1), [mockLifecycleDelegate scene:mockScene openURLContexts:urlContexts]);
  OCMVerify(times(1), [mockAppLifecycleDelegate sceneFallbackOpenURLContexts:urlContexts]);
  OCMVerify(times(1), [mockEngine sendDeepLinkToFramework:url completionHandler:[OCMArg any]]);
}

- (void)testSceneOpenURLContextsHandledByNoPlugin {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate =
      (FlutterEnginePluginSceneLifeCycleDelegate*)mocks[@"mockLifecycleDelegate"];
  id mockAppLifecycleDelegate = mocks[@"mockAppLifecycleDelegate"];
  OCMStub([mockLifecycleDelegate scene:[OCMArg any] openURLContexts:[OCMArg any]]).andReturn(NO);
  OCMStub([mockAppLifecycleDelegate sceneFallbackOpenURLContexts:[OCMArg any]]).andReturn(NO);
  id flutterApp = OCMClassMock([FlutterSharedApplication class]);
  OCMStub([flutterApp isFlutterDeepLinkingEnabled]).andReturn(NO);

  id urlContext = OCMClassMock([UIOpenURLContext class]);
  NSSet<UIOpenURLContext*>* urlContexts = [NSSet setWithObjects:urlContext, nil];

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);

  [delegate scene:mockScene openURLContexts:urlContexts];
  OCMVerify(times(1), [mockLifecycleDelegate scene:mockScene openURLContexts:urlContexts]);
  OCMVerify(times(1), [mockAppLifecycleDelegate sceneFallbackOpenURLContexts:urlContexts]);
}

- (void)testSceneOpenURLContextsWithMultipleEnginesSomeHandledByPlugin {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockScene = mocks[@"mockScene"];
  id mockAppLifecycleDelegate = mocks[@"mockAppLifecycleDelegate"];

  id mockEngine1 = OCMClassMock([FlutterEngine class]);
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate1 =
      OCMClassMock([FlutterEnginePluginSceneLifeCycleDelegate class]);
  OCMStub([mockEngine1 sceneLifeCycleDelegate]).andReturn(mockLifecycleDelegate1);
  OCMStub([mockLifecycleDelegate1 scene:[OCMArg any] openURLContexts:[OCMArg any]]).andReturn(YES);

  id mockEngine2 = OCMClassMock([FlutterEngine class]);
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate2 =
      OCMClassMock([FlutterEnginePluginSceneLifeCycleDelegate class]);
  OCMStub([mockEngine2 sceneLifeCycleDelegate]).andReturn(mockLifecycleDelegate2);
  OCMStub([mockLifecycleDelegate2 scene:[OCMArg any] openURLContexts:[OCMArg any]]).andReturn(NO);

  id flutterApp = OCMClassMock([FlutterSharedApplication class]);
  OCMStub([flutterApp isFlutterDeepLinkingEnabled]).andReturn(YES);

  NSURL* url = [NSURL URLWithString:@"example.com"];
  id urlContext = OCMClassMock([UIOpenURLContext class]);
  OCMStub([urlContext URL]).andReturn(url);
  NSSet<UIOpenURLContext*>* urlContexts = [NSSet setWithObjects:urlContext, nil];

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine1 scene:mockScene];
  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine2 scene:mockScene];

  [delegate scene:mockScene openURLContexts:urlContexts];

  OCMVerify(times(1), [mockLifecycleDelegate1 scene:mockScene openURLContexts:urlContexts]);
  OCMVerify(times(1), [mockLifecycleDelegate2 scene:mockScene openURLContexts:urlContexts]);
  OCMVerify(times(0), [mockAppLifecycleDelegate sceneFallbackOpenURLContexts:urlContexts]);
  OCMVerify(times(0), [mockEngine1 sendDeepLinkToFramework:url completionHandler:[OCMArg any]]);
  OCMVerify(times(1), [mockEngine2 sendDeepLinkToFramework:url completionHandler:[OCMArg any]]);
}

- (void)testSceneOpenURLContextsWithMultipleEnginesHandledByApplication {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockScene = mocks[@"mockScene"];
  id mockAppLifecycleDelegate = mocks[@"mockAppLifecycleDelegate"];
  OCMStub([mockAppLifecycleDelegate sceneFallbackOpenURLContexts:[OCMArg any]]).andReturn(YES);

  id mockEngine1 = OCMClassMock([FlutterEngine class]);
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate1 =
      OCMClassMock([FlutterEnginePluginSceneLifeCycleDelegate class]);
  OCMStub([mockEngine1 sceneLifeCycleDelegate]).andReturn(mockLifecycleDelegate1);
  OCMStub([mockLifecycleDelegate1 scene:[OCMArg any] openURLContexts:[OCMArg any]]).andReturn(NO);

  id mockEngine2 = OCMClassMock([FlutterEngine class]);
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate2 =
      OCMClassMock([FlutterEnginePluginSceneLifeCycleDelegate class]);
  OCMStub([mockEngine2 sceneLifeCycleDelegate]).andReturn(mockLifecycleDelegate2);
  OCMStub([mockLifecycleDelegate2 scene:[OCMArg any] openURLContexts:[OCMArg any]]).andReturn(NO);

  id flutterApp = OCMClassMock([FlutterSharedApplication class]);
  OCMStub([flutterApp isFlutterDeepLinkingEnabled]).andReturn(YES);

  NSURL* url = [NSURL URLWithString:@"example.com"];
  id urlContext = OCMClassMock([UIOpenURLContext class]);
  OCMStub([urlContext URL]).andReturn(url);
  NSSet<UIOpenURLContext*>* urlContexts = [NSSet setWithObjects:urlContext, nil];

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine1 scene:mockScene];
  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine2 scene:mockScene];

  [delegate scene:mockScene openURLContexts:urlContexts];

  OCMVerify(times(1), [mockLifecycleDelegate1 scene:mockScene openURLContexts:urlContexts]);
  OCMVerify(times(1), [mockLifecycleDelegate2 scene:mockScene openURLContexts:urlContexts]);
  OCMVerify(times(1), [mockAppLifecycleDelegate sceneFallbackOpenURLContexts:urlContexts]);
  OCMVerify(times(0), [mockEngine1 sendDeepLinkToFramework:url completionHandler:[OCMArg any]]);
  OCMVerify(times(0), [mockEngine2 sendDeepLinkToFramework:url completionHandler:[OCMArg any]]);
}

- (void)testSceneOpenURLContextsWithMultipleEnginesHandledByDeeplink {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockScene = mocks[@"mockScene"];
  id mockAppLifecycleDelegate = mocks[@"mockAppLifecycleDelegate"];
  OCMStub([mockAppLifecycleDelegate sceneFallbackOpenURLContexts:[OCMArg any]]).andReturn(NO);

  id mockEngine1 = OCMClassMock([FlutterEngine class]);
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate1 =
      OCMClassMock([FlutterEnginePluginSceneLifeCycleDelegate class]);
  OCMStub([mockEngine1 sceneLifeCycleDelegate]).andReturn(mockLifecycleDelegate1);
  OCMStub([mockLifecycleDelegate1 scene:[OCMArg any] openURLContexts:[OCMArg any]]).andReturn(NO);

  id mockEngine2 = OCMClassMock([FlutterEngine class]);
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate2 =
      OCMClassMock([FlutterEnginePluginSceneLifeCycleDelegate class]);
  OCMStub([mockEngine2 sceneLifeCycleDelegate]).andReturn(mockLifecycleDelegate2);
  OCMStub([mockLifecycleDelegate2 scene:[OCMArg any] openURLContexts:[OCMArg any]]).andReturn(NO);

  id flutterApp = OCMClassMock([FlutterSharedApplication class]);
  OCMStub([flutterApp isFlutterDeepLinkingEnabled]).andReturn(YES);

  NSURL* url = [NSURL URLWithString:@"example.com"];
  id urlContext = OCMClassMock([UIOpenURLContext class]);
  OCMStub([urlContext URL]).andReturn(url);
  NSSet<UIOpenURLContext*>* urlContexts = [NSSet setWithObjects:urlContext, nil];

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine1 scene:mockScene];
  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine2 scene:mockScene];

  [delegate scene:mockScene openURLContexts:urlContexts];

  OCMVerify(times(1), [mockLifecycleDelegate1 scene:mockScene openURLContexts:urlContexts]);
  OCMVerify(times(1), [mockLifecycleDelegate2 scene:mockScene openURLContexts:urlContexts]);
  OCMVerify(times(1), [mockAppLifecycleDelegate sceneFallbackOpenURLContexts:urlContexts]);
  OCMVerify(times(1), [mockEngine1 sendDeepLinkToFramework:url completionHandler:[OCMArg any]]);
  OCMVerify(times(1), [mockEngine2 sendDeepLinkToFramework:url completionHandler:[OCMArg any]]);
}

- (void)testSceneContinueUserActivityHandledByScenePlugin {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate =
      (FlutterEnginePluginSceneLifeCycleDelegate*)mocks[@"mockLifecycleDelegate"];
  id mockAppLifecycleDelegate = mocks[@"mockAppLifecycleDelegate"];
  OCMStub([mockLifecycleDelegate scene:[OCMArg any] continueUserActivity:[OCMArg any]])
      .andReturn(YES);
  OCMStub([mockAppLifecycleDelegate sceneFallbackContinueUserActivity:[OCMArg any]]).andReturn(YES);

  id userActivity = OCMClassMock([NSUserActivity class]);

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);

  [delegate scene:mockScene continueUserActivity:userActivity];
  OCMVerify(times(1), [mockLifecycleDelegate scene:mockScene continueUserActivity:userActivity]);
  OCMVerify(times(0), [mockAppLifecycleDelegate sceneFallbackContinueUserActivity:userActivity]);
}

- (void)testSceneContinueUserActivityHandledByApplicationPlugin {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate =
      (FlutterEnginePluginSceneLifeCycleDelegate*)mocks[@"mockLifecycleDelegate"];
  id mockAppLifecycleDelegate = mocks[@"mockAppLifecycleDelegate"];
  OCMStub([mockLifecycleDelegate scene:[OCMArg any] continueUserActivity:[OCMArg any]])
      .andReturn(NO);
  OCMStub([mockAppLifecycleDelegate sceneFallbackContinueUserActivity:[OCMArg any]]).andReturn(YES);

  id userActivity = OCMClassMock([NSUserActivity class]);

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);

  [delegate scene:mockScene continueUserActivity:userActivity];
  OCMVerify(times(1), [mockLifecycleDelegate scene:mockScene continueUserActivity:userActivity]);
  OCMVerify(times(1), [mockAppLifecycleDelegate sceneFallbackContinueUserActivity:userActivity]);
}

- (void)testSceneContinueUserActivityHandledByUniversalLinks {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate =
      (FlutterEnginePluginSceneLifeCycleDelegate*)mocks[@"mockLifecycleDelegate"];
  id mockAppLifecycleDelegate = mocks[@"mockAppLifecycleDelegate"];
  OCMStub([mockLifecycleDelegate scene:[OCMArg any] continueUserActivity:[OCMArg any]])
      .andReturn(NO);
  OCMStub([mockAppLifecycleDelegate sceneFallbackContinueUserActivity:[OCMArg any]]).andReturn(NO);
  id flutterApp = OCMClassMock([FlutterSharedApplication class]);
  OCMStub([flutterApp isFlutterDeepLinkingEnabled]).andReturn(YES);

  NSURL* url = [NSURL URLWithString:@"example.com"];
  id userActivity = OCMClassMock([NSUserActivity class]);
  OCMStub([userActivity webpageURL]).andReturn(url);

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);

  [delegate scene:mockScene continueUserActivity:userActivity];
  OCMVerify(times(1), [mockLifecycleDelegate scene:mockScene continueUserActivity:userActivity]);
  OCMVerify(times(1), [mockAppLifecycleDelegate sceneFallbackContinueUserActivity:userActivity]);
  OCMVerify(times(1), [mockEngine sendDeepLinkToFramework:url completionHandler:[OCMArg any]]);
}

- (void)testStateRestorationActivityForScene {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockViewController = OCMClassMock([FlutterViewController class]);
  id mockRestorationPlugin = OCMClassMock([FlutterRestorationPlugin class]);
  OCMStub([mockEngine viewController]).andReturn(mockViewController);
  OCMStub([mockEngine restorationPlugin]).andReturn(mockRestorationPlugin);

  NSString* restorationId = @"restorationId";
  NSString* mockDataString = @"mockData";
  NSString* configName = @"ConfigurationName";
  NSData* mockData = [mockDataString dataUsingEncoding:NSUTF8StringEncoding];
  OCMStub([mockViewController restorationIdentifier]).andReturn(restorationId);
  OCMStub([mockRestorationPlugin restorationData]).andReturn(mockData);

  id mockScene = mocks[@"mockScene"];
  id mockSession = mocks[@"mockSession"];
  id mockConfiguration = OCMClassMock([UISceneConfiguration class]);
  OCMStub([mockSession configuration]).andReturn(mockConfiguration);
  OCMStub([mockConfiguration name]).andReturn(configName);

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);
  NSUserActivity* state = [delegate stateRestorationActivityForScene:mockScene];
  XCTAssertEqual(state.userInfo[restorationId], mockData);
  XCTAssertEqual(state.activityType, configName);
}

- (void)testSceneRestoreInteractionStateWithUserActivity {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];
  id mockBundle = OCMPartialMock([NSBundle mainBundle]);
  id mockURL = OCMClassMock([NSURL class]);
  id mockFileDate = OCMClassMock([NSDate class]);
  int64_t mockBundleDateNum = 1;

  OCMStub([mockBundle executableURL]).andReturn(mockURL);
  OCMStub([mockURL getResourceValue:[OCMArg setTo:mockFileDate]
                             forKey:NSURLContentModificationDateKey
                              error:[OCMArg setTo:nil]]);
  OCMStub([mockFileDate timeIntervalSince1970]).andReturn(mockBundleDateNum);

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockViewController = OCMClassMock([FlutterViewController class]);
  id mockRestorationPlugin = OCMClassMock([FlutterRestorationPlugin class]);
  OCMStub([mockEngine viewController]).andReturn(mockViewController);
  OCMStub([mockEngine restorationPlugin]).andReturn(mockRestorationPlugin);

  NSString* restorationId = @"restorationId";
  NSString* mockDataString = @"teststring";
  NSNumber* mockBundleStateDateNum = @1.0;
  NSData* mockData = [mockDataString dataUsingEncoding:NSUTF8StringEncoding];
  OCMStub([mockViewController restorationIdentifier]).andReturn(restorationId);
  OCMStub([mockRestorationPlugin restorationData]).andReturn(mockData);

  id mockScene = mocks[@"mockScene"];

  id userActivity = OCMClassMock([NSUserActivity class]);
  NSDictionary* mockUserInfo = @{
    @"mod-date" : mockBundleStateDateNum,
    restorationId : mockData,
  };
  OCMStub([userActivity userInfo]).andReturn(mockUserInfo);

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);
  [delegate scene:mockScene restoreInteractionStateWithUserActivity:userActivity];
  OCMVerify(times(1), [mockRestorationPlugin setRestorationData:mockData]);
  [mockBundle stopMocking];
}

- (void)testSceneDoesNotRestoreInteractionStateWithUserActivity {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];
  id mockBundle = OCMPartialMock([NSBundle mainBundle]);
  id mockURL = OCMClassMock([NSURL class]);
  id mockFileDate = OCMClassMock([NSDate class]);
  int64_t mockBundleDateNum = 1;

  OCMStub([mockBundle executableURL]).andReturn(mockURL);
  OCMStub([mockURL getResourceValue:[OCMArg setTo:mockFileDate]
                             forKey:NSURLContentModificationDateKey
                              error:[OCMArg setTo:nil]]);
  OCMStub([mockFileDate timeIntervalSince1970]).andReturn(mockBundleDateNum);

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockViewController = OCMClassMock([FlutterViewController class]);
  id mockRestorationPlugin = OCMClassMock([FlutterRestorationPlugin class]);
  OCMStub([mockEngine viewController]).andReturn(mockViewController);
  OCMStub([mockEngine restorationPlugin]).andReturn(mockRestorationPlugin);

  NSString* restorationId = @"restorationId";
  NSString* mockDataString = @"teststring";
  NSNumber* mockBundleStateDateNum = @2.0;
  NSData* mockData = [mockDataString dataUsingEncoding:NSUTF8StringEncoding];
  OCMStub([mockViewController restorationIdentifier]).andReturn(restorationId);
  OCMStub([mockRestorationPlugin restorationData]).andReturn(mockData);

  id mockScene = mocks[@"mockScene"];

  id userActivity = OCMClassMock([NSUserActivity class]);
  NSDictionary* mockUserInfo = @{
    @"mod-date" : mockBundleStateDateNum,
    restorationId : mockData,
  };
  OCMStub([userActivity userInfo]).andReturn(mockUserInfo);

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);
  [delegate scene:mockScene restoreInteractionStateWithUserActivity:userActivity];
  OCMVerify(times(0), [mockRestorationPlugin setRestorationData:mockData]);
  [mockBundle stopMocking];
}

- (void)testSceneContinueUserActivityHandledByNoPlugin {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate =
      (FlutterEnginePluginSceneLifeCycleDelegate*)mocks[@"mockLifecycleDelegate"];
  id mockAppLifecycleDelegate = mocks[@"mockAppLifecycleDelegate"];
  OCMStub([mockLifecycleDelegate scene:[OCMArg any] continueUserActivity:[OCMArg any]])
      .andReturn(NO);
  OCMStub([mockAppLifecycleDelegate sceneFallbackContinueUserActivity:[OCMArg any]]).andReturn(NO);
  id flutterApp = OCMClassMock([FlutterSharedApplication class]);
  OCMStub([flutterApp isFlutterDeepLinkingEnabled]).andReturn(NO);

  NSURL* url = [NSURL URLWithString:@"example.com"];
  id userActivity = OCMClassMock([NSUserActivity class]);
  OCMStub([userActivity webpageURL]).andReturn(url);

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);

  [delegate scene:mockScene continueUserActivity:userActivity];
  OCMVerify(times(1), [mockLifecycleDelegate scene:mockScene continueUserActivity:userActivity]);
  OCMVerify(times(1), [mockAppLifecycleDelegate sceneFallbackContinueUserActivity:userActivity]);
  OCMVerify(times(0), [mockEngine sendDeepLinkToFramework:url completionHandler:[OCMArg any]]);
}

- (void)testWindowScenePerformActionForShortcutItemHandledByScenePlugin {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate =
      (FlutterEnginePluginSceneLifeCycleDelegate*)mocks[@"mockLifecycleDelegate"];
  id mockAppLifecycleDelegate = mocks[@"mockAppLifecycleDelegate"];
  OCMStub([mockLifecycleDelegate windowScene:[OCMArg any]
                performActionForShortcutItem:[OCMArg any]
                           completionHandler:[OCMArg any]])
      .andReturn(YES);
  OCMStub([mockAppLifecycleDelegate sceneFallbackPerformActionForShortcutItem:[OCMArg any]
                                                            completionHandler:[OCMArg any]])
      .andReturn(YES);

  id shortcutItem = OCMClassMock([UIApplicationShortcutItem class]);
  id handler = ^(BOOL succeeded) {
  };

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);

  [delegate windowScene:mockScene
      performActionForShortcutItem:shortcutItem
                 completionHandler:handler];
  OCMVerify(times(1), [mockLifecycleDelegate windowScene:mockScene
                            performActionForShortcutItem:shortcutItem
                                       completionHandler:handler]);
  OCMVerify(times(0),
            [mockAppLifecycleDelegate sceneFallbackPerformActionForShortcutItem:shortcutItem
                                                              completionHandler:handler]);
}

- (void)testWindowScenePerformActionForShortcutItemHandledByApplicationPlugin {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate =
      (FlutterEnginePluginSceneLifeCycleDelegate*)mocks[@"mockLifecycleDelegate"];
  id mockAppLifecycleDelegate = mocks[@"mockAppLifecycleDelegate"];
  OCMStub([mockLifecycleDelegate windowScene:[OCMArg any]
                performActionForShortcutItem:[OCMArg any]
                           completionHandler:[OCMArg any]])
      .andReturn(NO);
  OCMStub([mockAppLifecycleDelegate sceneFallbackPerformActionForShortcutItem:[OCMArg any]
                                                            completionHandler:[OCMArg any]])
      .andReturn(YES);

  id shortcutItem = OCMClassMock([UIApplicationShortcutItem class]);
  id handler = ^(BOOL succeeded) {
  };

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);

  [delegate windowScene:mockScene
      performActionForShortcutItem:shortcutItem
                 completionHandler:handler];
  OCMVerify(times(1), [mockLifecycleDelegate windowScene:mockScene
                            performActionForShortcutItem:shortcutItem
                                       completionHandler:handler]);
  OCMVerify(times(1),
            [mockAppLifecycleDelegate sceneFallbackPerformActionForShortcutItem:shortcutItem
                                                              completionHandler:handler]);
}

- (void)testWindowScenePerformActionForShortcutItemHandledByNoPlugin {
  FlutterPluginSceneLifeCycleDelegate* delegate =
      [[FlutterPluginSceneLifeCycleDelegate alloc] init];

  id mocks = [self mocksForEvents];
  id mockEngine = mocks[@"mockEngine"];
  id mockScene = mocks[@"mockScene"];
  FlutterEnginePluginSceneLifeCycleDelegate* mockLifecycleDelegate =
      (FlutterEnginePluginSceneLifeCycleDelegate*)mocks[@"mockLifecycleDelegate"];
  id mockAppLifecycleDelegate = mocks[@"mockAppLifecycleDelegate"];
  OCMStub([mockLifecycleDelegate windowScene:[OCMArg any]
                performActionForShortcutItem:[OCMArg any]
                           completionHandler:[OCMArg any]])
      .andReturn(NO);
  OCMStub([mockAppLifecycleDelegate sceneFallbackPerformActionForShortcutItem:[OCMArg any]
                                                            completionHandler:[OCMArg any]])
      .andReturn(NO);

  id shortcutItem = OCMClassMock([UIApplicationShortcutItem class]);
  id handler = ^(BOOL succeeded) {
  };

  [delegate registerSceneLifeCycleWithFlutterEngine:mockEngine scene:mockScene];
  XCTAssertEqual([delegate searchFlutterEnginesWithScene:mockScene].count, 1.0);

  [delegate windowScene:mockScene
      performActionForShortcutItem:shortcutItem
                 completionHandler:handler];
  OCMVerify(times(1), [mockLifecycleDelegate windowScene:mockScene
                            performActionForShortcutItem:shortcutItem
                                       completionHandler:handler]);
  OCMVerify(times(1),
            [mockAppLifecycleDelegate sceneFallbackPerformActionForShortcutItem:shortcutItem
                                                              completionHandler:handler]);
}

- (NSDictionary*)mocksForEvents {
  id mockEngine = OCMClassMock([FlutterEngine class]);
  id mockLifecycleDelegate = OCMClassMock([FlutterEnginePluginSceneLifeCycleDelegate class]);
  OCMStub([mockEngine sceneLifeCycleDelegate]).andReturn(mockLifecycleDelegate);

  id mockApplication = OCMClassMock([UIApplication class]);
  OCMStub([mockApplication sharedApplication]).andReturn(mockApplication);
  OCMStub([mockApplication supportsMultipleScenes]).andReturn(YES);

  id mockAppDelegate = OCMClassMock([FlutterAppDelegate class]);
  OCMStub([mockApplication delegate]).andReturn(mockAppDelegate);

  id mockAppLifecycleDelegate = OCMClassMock([FlutterPluginAppLifeCycleDelegate class]);
  OCMStub([mockAppDelegate lifeCycleDelegate]).andReturn(mockAppLifecycleDelegate);

  id mockScene = OCMClassMock([UIWindowScene class]);
  id mockSession = OCMClassMock([UISceneSession class]);
  OCMStub([mockScene session]).andReturn(mockSession);

  return @{
    @"mockEngine" : mockEngine,
    @"mockScene" : mockScene,
    @"mockSession" : mockSession,
    @"mockLifecycleDelegate" : mockLifecycleDelegate,
    @"mockAppLifecycleDelegate" : mockAppLifecycleDelegate,
  };
}

#pragma mark - FlutterEnginePluginSceneLifeCycleDelegate

- (void)testEngineSceneWillConnectToSession {
  FlutterEnginePluginSceneLifeCycleDelegate* delegate =
      [[FlutterEnginePluginSceneLifeCycleDelegate alloc] init];

  NSObject<FlutterSceneLifeCycleDelegate>* mockPlugin =
      OCMProtocolMock(@protocol(FlutterSceneLifeCycleDelegate));
  OCMStub([mockPlugin scene:[OCMArg any] willConnectToSession:[OCMArg any] options:[OCMArg any]])
      .andReturn(YES);
  NSObject<FlutterSceneLifeCycleDelegate>* mockPlugin2 =
      OCMProtocolMock(@protocol(FlutterSceneLifeCycleDelegate));
  OCMStub([mockPlugin2 scene:[OCMArg any] willConnectToSession:[OCMArg any] options:[OCMArg any]])
      .andReturn(YES);

  [delegate addDelegate:mockPlugin];
  [delegate addDelegate:mockPlugin2];

  id mockScene = OCMClassMock([UIWindowScene class]);
  id mockSession = OCMClassMock([UISceneSession class]);
  id mockOptions = OCMClassMock([UISceneConnectionOptions class]);

  XCTAssertTrue([delegate scene:mockScene willConnectToSession:mockSession options:mockOptions]);
  OCMVerify(times(1), [mockPlugin scene:mockScene
                          willConnectToSession:mockSession
                                       options:mockOptions]);
  OCMVerify(times(1), [mockPlugin2 scene:mockScene willConnectToSession:mockSession options:nil]);
}

- (void)testEngineSceneDidDisconnect {
  FlutterEnginePluginSceneLifeCycleDelegate* delegate =
      [[FlutterEnginePluginSceneLifeCycleDelegate alloc] init];

  id mockPlugin = OCMProtocolMock(@protocol(FlutterSceneLifeCycleDelegate));
  [delegate addDelegate:mockPlugin];
  id mockScene = OCMClassMock([UIWindowScene class]);
  [delegate sceneDidDisconnect:mockScene];
  OCMVerify([mockPlugin sceneDidDisconnect:mockScene]);
}

- (void)testEngineSceneWillEnterForeground {
  FlutterEnginePluginSceneLifeCycleDelegate* delegate =
      [[FlutterEnginePluginSceneLifeCycleDelegate alloc] init];

  id mockPlugin = OCMProtocolMock(@protocol(FlutterSceneLifeCycleDelegate));
  [delegate addDelegate:mockPlugin];
  id mockScene = OCMClassMock([UIWindowScene class]);
  [delegate sceneWillEnterForeground:mockScene];
  OCMVerify([mockPlugin sceneWillEnterForeground:mockScene]);
}

- (void)testEngineSceneDidBecomeActive {
  FlutterEnginePluginSceneLifeCycleDelegate* delegate =
      [[FlutterEnginePluginSceneLifeCycleDelegate alloc] init];

  id mockPlugin = OCMProtocolMock(@protocol(FlutterSceneLifeCycleDelegate));
  [delegate addDelegate:mockPlugin];
  id mockScene = OCMClassMock([UIWindowScene class]);
  [delegate sceneDidBecomeActive:mockScene];
  OCMVerify([mockPlugin sceneDidBecomeActive:mockScene]);
}

- (void)testEngineSceneWillResignActive {
  FlutterEnginePluginSceneLifeCycleDelegate* delegate =
      [[FlutterEnginePluginSceneLifeCycleDelegate alloc] init];

  id mockPlugin = OCMProtocolMock(@protocol(FlutterSceneLifeCycleDelegate));
  [delegate addDelegate:mockPlugin];
  id mockScene = OCMClassMock([UIWindowScene class]);
  [delegate sceneWillResignActive:mockScene];
  OCMVerify([mockPlugin sceneWillResignActive:mockScene]);
}

- (void)testEngineSceneDidEnterBackground {
  FlutterEnginePluginSceneLifeCycleDelegate* delegate =
      [[FlutterEnginePluginSceneLifeCycleDelegate alloc] init];

  id mockPlugin = OCMProtocolMock(@protocol(FlutterSceneLifeCycleDelegate));
  [delegate addDelegate:mockPlugin];
  id mockScene = OCMClassMock([UIWindowScene class]);
  [delegate sceneDidEnterBackground:mockScene];
  OCMVerify([mockPlugin sceneDidEnterBackground:mockScene]);
}

- (void)testEngineSceneOpenURLContexts {
  FlutterEnginePluginSceneLifeCycleDelegate* delegate =
      [[FlutterEnginePluginSceneLifeCycleDelegate alloc] init];

  NSObject<FlutterSceneLifeCycleDelegate>* mockPlugin =
      OCMProtocolMock(@protocol(FlutterSceneLifeCycleDelegate));
  OCMStub([mockPlugin scene:[OCMArg any] openURLContexts:[OCMArg any]]).andReturn(YES);
  NSObject<FlutterSceneLifeCycleDelegate>* mockPlugin2 =
      OCMProtocolMock(@protocol(FlutterSceneLifeCycleDelegate));
  OCMStub([mockPlugin2 scene:[OCMArg any] openURLContexts:[OCMArg any]]).andReturn(YES);

  [delegate addDelegate:mockPlugin];
  [delegate addDelegate:mockPlugin2];

  id mockScene = OCMClassMock([UIWindowScene class]);
  id urlContext = OCMClassMock([UIOpenURLContext class]);
  NSSet<UIOpenURLContext*>* urlContexts = [NSSet setWithObjects:urlContext, nil];

  XCTAssertTrue([delegate scene:mockScene openURLContexts:urlContexts]);
  OCMVerify(times(1), [mockPlugin scene:mockScene openURLContexts:urlContexts]);
  OCMVerify(times(0), [mockPlugin2 scene:mockScene openURLContexts:urlContexts]);
}

- (void)testEngineSceneContinueUserActivity {
  FlutterEnginePluginSceneLifeCycleDelegate* delegate =
      [[FlutterEnginePluginSceneLifeCycleDelegate alloc] init];

  NSObject<FlutterSceneLifeCycleDelegate>* mockPlugin =
      OCMProtocolMock(@protocol(FlutterSceneLifeCycleDelegate));
  OCMStub([mockPlugin scene:[OCMArg any] continueUserActivity:[OCMArg any]]).andReturn(YES);
  NSObject<FlutterSceneLifeCycleDelegate>* mockPlugin2 =
      OCMProtocolMock(@protocol(FlutterSceneLifeCycleDelegate));
  OCMStub([mockPlugin2 scene:[OCMArg any] continueUserActivity:[OCMArg any]]).andReturn(YES);

  [delegate addDelegate:mockPlugin];
  [delegate addDelegate:mockPlugin2];

  id mockScene = OCMClassMock([UIWindowScene class]);
  id userActivity = OCMClassMock([NSUserActivity class]);

  XCTAssertTrue([delegate scene:mockScene continueUserActivity:userActivity]);
  OCMVerify(times(1), [mockPlugin scene:mockScene continueUserActivity:userActivity]);
  OCMVerify(times(0), [mockPlugin2 scene:mockScene continueUserActivity:userActivity]);
}

- (void)testEngineWindowScenePerformActionForShortcutItem {
  FlutterEnginePluginSceneLifeCycleDelegate* delegate =
      [[FlutterEnginePluginSceneLifeCycleDelegate alloc] init];

  NSObject<FlutterSceneLifeCycleDelegate>* mockPlugin =
      OCMProtocolMock(@protocol(FlutterSceneLifeCycleDelegate));
  OCMStub([mockPlugin windowScene:[OCMArg any]
              performActionForShortcutItem:[OCMArg any]
                         completionHandler:[OCMArg any]])
      .andReturn(YES);
  NSObject<FlutterSceneLifeCycleDelegate>* mockPlugin2 =
      OCMProtocolMock(@protocol(FlutterSceneLifeCycleDelegate));
  OCMStub([mockPlugin2 windowScene:[OCMArg any]
              performActionForShortcutItem:[OCMArg any]
                         completionHandler:[OCMArg any]])
      .andReturn(YES);

  [delegate addDelegate:mockPlugin];
  [delegate addDelegate:mockPlugin2];

  id mockScene = OCMClassMock([UIWindowScene class]);
  id shortcutItem = OCMClassMock([UIApplicationShortcutItem class]);
  id handler = ^(BOOL succeeded) {
  };

  XCTAssertTrue([delegate windowScene:mockScene
         performActionForShortcutItem:shortcutItem
                    completionHandler:handler]);
  OCMVerify(times(1), [mockPlugin windowScene:mockScene
                          performActionForShortcutItem:shortcutItem
                                     completionHandler:handler]);
  OCMVerify(times(0), [mockPlugin2 windowScene:mockScene
                          performActionForShortcutItem:shortcutItem
                                     completionHandler:handler]);
}

@end
