[workspace]
members = [
  "crates/flutter-plugin-sdk",
  "crates/flutter-shell-android-runner",
  "crates/flutter-shell-core",
  "crates/flutter-shell-wgpu",
  "crates/flutter-shell-winit",
]
resolver = "3"

[patch.crates-io]
winit-wayland = { path = "third_party/winit-wayland" }

[workspace.package]
edition = "2024"
rust-version = "1.93"
license = "BSD-3-Clause"
