[package]
name = "flutter-shell-winit"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Winit host runtime for the Flutter Rust shell"

[lib]
crate-type = ["rlib", "staticlib"]
path = "src/lib.rs"

[dependencies]
async-trait = "=0.1.89"
flutter-plugin-sdk = { path = "../flutter-plugin-sdk", version = "0.1.0" }
flutter-shell-core = { path = "../flutter-shell-core", version = "0.1.0" }
flutter-shell-wgpu = { path = "../flutter-shell-wgpu", version = "0.1.0" }
log = "=0.4.33"
parking_lot = "=0.12.5"
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.149"

[target.'cfg(target_os = "linux")'.dependencies]
raw-window-handle = "=0.6.2"
wgpu = { git = "https://github.com/gfx-rs/wgpu.git", rev = "014d9e84813a2946febfa4888694c0b70565b2f5", default-features = false, features = ["vulkan"] }
wayland-sys = { version = "=0.31.11", features = ["client", "dlopen"] }
winit = { version = "=0.31.0-beta.2", default-features = false, features = [
  "wayland",
  "wayland-csd-adwaita",
  "wayland-dlopen",
  "x11",
] }
x11-dl = "=2.21.0"

[target.'cfg(target_os = "android")'.dependencies]
raw-window-handle = "=0.6.2"
wgpu = { git = "https://github.com/gfx-rs/wgpu.git", rev = "014d9e84813a2946febfa4888694c0b70565b2f5", default-features = false, features = ["vulkan"] }
winit = { version = "=0.31.0-beta.2", default-features = false, features = [
  "android-game-activity",
] }
