// Copyright 2018 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE DO NOT EDIT!
// This file was generated by vitool.
part of material_animated_icons;
const _AnimatedIconData _$play_pause = const _AnimatedIconData(
  const Size(48.0, 48.0),
  const <_PathFrames>[
    const _PathFrames(
      opacities: const <double>[
        1.0,
        1.0,
        1.0,
        1.0,
      ],
      commands: const <_PathCommand>[
        const _PathMoveTo(
          const <Offset>[
            const Offset(16.046875, 10.039062500000002),
            const Offset(22.581365240485308, 7.589125591600418),
            const Offset(32.55729037951853, 7.8522502852455425),
            const Offset(35.71938467416858, 9.764269500343072),
          ],
        ),
        const _PathCubicTo(
          const <Offset>[
            const Offset(16.046875, 10.039062500000002),
            const Offset(22.581365240485308, 7.589125591600418),
            const Offset(32.55729037951853, 7.8522502852455425),
            const Offset(35.71938467416858, 9.764269500343072),
          ],
          const <Offset>[
            const Offset(16.046875, 24.0),
            const Offset(16.312852147291277, 18.33792251536507),
            const Offset(24.48905576105046, 9.794101160418514),
            const Offset(27.720964836869285, 9.92326668993185),
          ],
          const <Offset>[
            const Offset(16.046875, 24.0),
            const Offset(16.312852147291277, 18.33792251536507),
            const Offset(24.48905576105046, 9.794101160418514),
            const Offset(27.720964836869285, 9.92326668993185),
          ],
        ),
        const _PathCubicTo(
          const <Offset>[
            const Offset(16.046875, 24.0),
            const Offset(16.312852147291277, 18.33792251536507),
            const Offset(24.48905576105046, 9.794101160418514),
            const Offset(27.720964836869285, 9.92326668993185),
          ],
          const <Offset>[
            const Offset(37.984375, 24.0),
            const Offset(36.59673961336577, 30.16713606026377),
            const Offset(30.969894470496282, 36.721466129987085),
            const Offset(28.27745500043001, 37.91773612047938),
          ],
          const <Offset>[
            const Offset(37.984375, 24.0),
            const Offset(36.59673961336577, 30.16713606026377),
            const Offset(30.969894470496282, 36.721466129987085),
            const Offset(28.27745500043001, 37.91773612047938),
          ],
        ),
        const _PathCubicTo(
          const <Offset>[
            const Offset(37.984375, 24.0),
            const Offset(36.59673961336577, 30.16713606026377),
            const Offset(30.969894470496282, 36.721466129987085),
            const Offset(28.27745500043001, 37.91773612047938),
          ],
          const <Offset>[
            const Offset(37.984375, 24.0),
            const Offset(37.62294586290445, 28.407471142252255),
            const Offset(38.35814295213548, 34.94327332096457),
            const Offset(36.275874837729305, 37.7587389308906),
          ],
          const <Offset>[
            const Offset(37.984375, 24.0),
            const Offset(37.62294586290445, 28.407471142252255),
            const Offset(38.35814295213548, 34.94327332096457),
            const Offset(36.275874837729305, 37.7587389308906),
          ],
        ),
        const _PathCubicTo(
          const <Offset>[
            const Offset(37.984375, 24.0),
            const Offset(37.62294586290445, 28.407471142252255),
            const Offset(38.35814295213548, 34.94327332096457),
            const Offset(36.275874837729305, 37.7587389308906),
          ],
          const <Offset>[
            const Offset(16.046875, 10.039062500000002),
            const Offset(22.58136524050546, 7.589125591565864),
            const Offset(32.55729037951755, 7.852250285245777),
            const Offset(35.71938467416858, 9.764269500343072),
          ],
          const <Offset>[
            const Offset(16.046875, 10.039062500000002),
            const Offset(22.58136524050546, 7.589125591565864),
            const Offset(32.55729037951755, 7.852250285245777),
            const Offset(35.71938467416858, 9.764269500343072),
          ],
        ),
        const _PathClose(
        ),
      ],
    ),
    const _PathFrames(
      opacities: const <double>[
        1.0,
        1.0,
        1.0,
        1.0,
      ],
      commands: const <_PathCommand>[
        const _PathMoveTo(
          const <Offset>[
            const Offset(37.984375, 24.0),
            const Offset(35.57053336387648, 31.926800978315658),
            const Offset(23.581645988882627, 38.49965893899394),
            const Offset(20.279035163130715, 38.07673331006816),
          ],
        ),
        const _PathCubicTo(
          const <Offset>[
            const Offset(37.984375, 24.0),
            const Offset(35.57053336387648, 31.926800978315658),
            const Offset(23.581645988882627, 38.49965893899394),
            const Offset(20.279035163130715, 38.07673331006816),
          ],
          const <Offset>[
            const Offset(16.046875, 24.0),
            const Offset(15.286645897801982, 20.097587433416958),
            const Offset(17.100807279436804, 11.57229396942536),
            const Offset(19.722544999569994, 10.082263879520628),
          ],
          const <Offset>[
            const Offset(16.046875, 24.0),
            const Offset(15.286645897801982, 20.097587433416958),
            const Offset(17.100807279436804, 11.57229396942536),
            const Offset(19.722544999569994, 10.082263879520628),
          ],
        ),
        const _PathCubicTo(
          const <Offset>[
            const Offset(16.046875, 24.0),
            const Offset(15.286645897801982, 20.097587433416958),
            const Offset(17.100807279436804, 11.57229396942536),
            const Offset(19.722544999569994, 10.082263879520628),
          ],
          const <Offset>[
            const Offset(16.046875, 37.9609375),
            const Offset(9.018132804607959, 30.846384357181606),
            const Offset(9.032572660968736, 13.51414484459833),
            const Offset(11.724125162270699, 10.241261069109406),
          ],
          const <Offset>[
            const Offset(16.046875, 37.9609375),
            const Offset(9.018132804607959, 30.846384357181606),
            const Offset(9.032572660968736, 13.51414484459833),
            const Offset(11.724125162270699, 10.241261069109406),
          ],
        ),
        const _PathCubicTo(
          const <Offset>[
            const Offset(16.046875, 37.9609375),
            const Offset(9.018132804607959, 30.846384357181606),
            const Offset(9.032572660968736, 13.51414484459833),
            const Offset(11.724125162270699, 10.241261069109406),
          ],
          const <Offset>[
            const Offset(37.984375, 24.0),
            const Offset(34.544327114357955, 33.68646589629262),
            const Offset(16.193397507242462, 40.27785174801669),
            const Offset(12.280615325831423, 38.23573049965694),
          ],
          const <Offset>[
            const Offset(37.984375, 24.0),
            const Offset(34.544327114357955, 33.68646589629262),
            const Offset(16.193397507242462, 40.27785174801669),
            const Offset(12.280615325831423, 38.23573049965694),
          ],
        ),
        const _PathCubicTo(
          const <Offset>[
            const Offset(37.984375, 24.0),
            const Offset(34.544327114357955, 33.68646589629262),
            const Offset(16.193397507242462, 40.27785174801669),
            const Offset(12.280615325831423, 38.23573049965694),
          ],
          const <Offset>[
            const Offset(37.984375, 24.0),
            const Offset(35.57053336389663, 31.9268009782811),
            const Offset(23.58164598888166, 38.49965893899417),
            const Offset(20.279035163130715, 38.07673331006816),
          ],
          const <Offset>[
            const Offset(37.984375, 24.0),
            const Offset(35.57053336389663, 31.9268009782811),
            const Offset(23.58164598888166, 38.49965893899417),
            const Offset(20.279035163130715, 38.07673331006816),
          ],
        ),
        const _PathClose(
        ),
      ],
    ),
    const _PathFrames(
      opacities: const <double>[
        1.0,
        0.733333333333,
        0.0,
        0.0,
      ],
      commands: const <_PathCommand>[
        const _PathMoveTo(
          const <Offset>[
            const Offset(36.21875, 24.387283325200002),
            const Offset(35.51445214909996, 31.937043103050268),
            const Offset(26.23678799810123, 37.80492814052796),
            const Offset(23.221743554700737, 37.96329396736102),
          ],
        ),
        const _PathCubicTo(
          const <Offset>[
            const Offset(36.21875, 24.387283325200002),
            const Offset(35.51445214909996, 31.937043103050268),
            const Offset(26.23678799810123, 37.80492814052796),
            const Offset(23.221743554700737, 37.96329396736102),
          ],
          const <Offset>[
            const Offset(36.1819000244141, 23.597152709966),
            const Offset(36.67279396166709, 30.08280087402087),
            const Offset(28.376981306736234, 37.3582262261251),
            const Offset(25.407936267815487, 37.98634651128109),
          ],
          const <Offset>[
            const Offset(36.1819000244141, 23.597152709966),
            const Offset(36.67279396166709, 30.08280087402087),
            const Offset(28.376981306736234, 37.3582262261251),
            const Offset(25.407936267815487, 37.98634651128109),
          ],
        ),
        const _PathCubicTo(
          const <Offset>[
            const Offset(36.1819000244141, 23.597152709966),
            const Offset(36.67279396166709, 30.08280087402087),
            const Offset(28.376981306736234, 37.3582262261251),
            const Offset(25.407936267815487, 37.98634651128109),
          ],
          const <Offset>[
            const Offset(16.1149902344141, 22.955383300786004),
            const Offset(16.769441289779344, 18.37084947089115),
            const Offset(23.06110116092593, 14.884804779309462),
            const Offset(25.03935354219434, 14.895712045654406),
          ],
          const <Offset>[
            const Offset(16.170043945314102, 22.942321777349),
            const Offset(16.82882476693832, 18.390360508490243),
            const Offset(23.0881035089048, 14.941178098808248),
            const Offset(25.053627357583, 14.956567087696417),
          ],
        ),
        const _PathCubicTo(
          const <Offset>[
            const Offset(16.225097656251602, 22.9292602539115),
            const Offset(16.888208244083728, 18.409871546081646),
            const Offset(23.11510585687983, 14.997551418291916),
            const Offset(25.067901172971148, 15.017422129722831),
          ],
          const <Offset>[
            const Offset(16.172653198243793, 25.050704956059),
            const Offset(15.534079923477577, 20.72510957725349),
            const Offset(20.506617505527394, 15.621874388004521),
            const Offset(22.386204205776483, 15.067342323943635),
          ],
          const <Offset>[
            const Offset(16.172653198243804, 25.050704956059),
            const Offset(15.534079923477577, 20.72510957725349),
            const Offset(20.506617505527394, 15.621874388004521),
            const Offset(22.386204205776483, 15.067342323943635),
          ],
        ),
        const _PathCubicTo(
          const <Offset>[
            const Offset(16.172653198243804, 25.050704956059),
            const Offset(15.534079923477577, 20.72510957725349),
            const Offset(20.506617505527394, 15.621874388004521),
            const Offset(22.386204205776483, 15.067342323943635),
          ],
          const <Offset>[
            const Offset(36.218750000043805, 24.387283325200002),
            const Offset(35.51445214905712, 31.937043103018333),
            const Offset(26.23678799809464, 37.80492814047493),
            const Offset(23.221743554705682, 37.96329396730781),
          ],
          const <Offset>[
            const Offset(36.218750000043805, 24.387283325200002),
            const Offset(35.51445214905712, 31.937043103018333),
            const Offset(26.23678799809464, 37.80492814047493),
            const Offset(23.221743554705682, 37.96329396730781),
          ],
        ),
        const _PathClose(
        ),
      ],
    ),
  ],
);
