analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: ../analysis_options.yaml

linter:
  rules:
    - unawaited_futures
