platform :ios, '9.0'

target 'Host' do
  flutter_application_path = '../hello'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  install_all_flutter_pods flutter_application_path
end
