name: primitive_shape_test
description: Integration test to capture primitive shape rendering snapshots and upload to Skia Gold.
publish_to: none

environment:
  sdk: ^3.11.0-0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  path: any

dev_dependencies:
  flutter_goldens:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any

# PUBSPEC CHECKSUM: fp4cre
