// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
  Constructor(),
  PrivateDart,
] interface ParagraphBuilder {
  void pushStyle(Int32List encoded, DOMString fontFamily, double fontSize, double letterSpacing);
  void pop();

  void addText(DOMString text);

  Paragraph build(Int32List encoded, double lineHeight);
};
