// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:async';

import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:leak_tracker/leak_tracker.dart';
import 'package:leak_tracker_flutter_testing/leak_tracker_flutter_testing.dart';

import '_goldens_io.dart'
  if (dart.library.html) '_goldens_web.dart' as flutter_goldens;

/// Test configuration for each test library in this directory.
///
/// See https://api.flutter.dev/flutter/flutter_test/flutter_test-library.html.
Future<void> testExecutable(FutureOr<void> Function() testMain) {
  // Enable checks because there are many implementations of [RenderBox] in this
  // package can benefit from the additional validations.
  debugCheckIntrinsicSizes = true;

  // Make tap() et al fail if the given finder specifies a widget that would not
  // receive the event.
  WidgetController.hitTestWarningShouldBeFatal = true;

  LeakTracking.warnForUnsupportedPlatforms = false;

  // TODO(polina-c): clean up leaks and delete ignored classes from settings.
  // https://github.com/flutter/flutter/issues/137311
  LeakTesting.settings = LeakTesting
    .settings
    .withTrackedAll()
    .withIgnored(
      notGCed: <String, int?>{
        'AnimationController': null,
        'ChangeNotifier': null,
        'ChangerState': null,
        'ClipboardStatusNotifier': null,
        'CupertinoPageRoute<dynamic>': null,
        'CupertinoTabController': null,
        'DialogRoute<DateTimeRange>': null,
        'DrawerControllerState': null,
        'EditableTextState': null,
        'FixedExtentScrollController': null,
        'FocusNode': null,
        'FocusScopeNode': null,
        'InheritedElement': null,
        'InheritedModelElement<Object>': null,
        'InheritedModelElement<_MediaQueryAspect>': null,
        'InheritedModelElement<_TimePickerAspect>': null,
        'LeafRenderObjectElement': null,
        'ListWheelElement': null,
        'LiveTextInputStatusNotifier': null,
        'MaterialPageRoute<dynamic>': null,
        'MaterialStatesController': null,
        'MultiChildRenderObjectElement': null,
        'NavigatorState': null,
        'NestedScrollViewState': null,
        'OffsetLayer': null,
        'OverlayEntry': null,
        'OverlayState': null,
        'PageController': null,
        'PageRouteBuilder<void>': null,
        'ParentDataElement<FlexParentData>': null,
        'ParentDataElement<KeepAliveParentDataMixin>': null,
        'ParentDataElement<MultiChildLayoutParentData>': null,
        'ParentDataElement<SliverPhysicalParentData>': null,
        'ParentDataElement<StackParentData>': null,
        'RawGestureDetectorState': null,
        'RenderAbsorbPointer': null,
        'RenderAndroidView': null,
        'RenderAnimatedOpacity': null,
        'RenderAnimatedSize': null,
        'RenderAnnotatedRegion<SystemUiOverlayStyle>': null,
        'RenderBackdropFilter': null,
        'RenderBlockSemantics': null,
        'RenderBox>': null,
        'RenderClipPath': null,
        'RenderClipRect': null,
        'RenderConstrainedBox': null,
        'RenderConstrainedOverflowBox': null,
        'RenderConstraintsTransformBox': null,
        'RenderCustomMultiChildLayoutBox': null,
        'RenderCustomPaint': null,
        'RenderCustomSingleChildLayoutBox': null,
        'RenderDecoratedBox': null,
        'RenderEditable': null,
        'RenderExcludeSemantics': null,
        'RenderFlex': null,
        'RenderFollowerLayer': null,
        'RenderFractionalTranslation': null,
        'RenderIgnorePointer': null,
        'RenderImage': null,
        'RenderIndexedSemantics': null,
        'RenderIntrinsicHeight': null,
        'RenderIntrinsicWidth': null,
        'RenderLeaderLayer': null,
        'RenderLimitedBox': null,
        'RenderListBody': null,
        'RenderListWheelViewport': null,
        'RenderMergeSemantics': null,
        'RenderMetaData': null,
        'RenderMouseRegion': null,
        'RenderNestedScrollViewViewport': null,
        'RenderOffstage': null,
        'RenderPadding': null,
        'RenderParagraph': null,
        'RenderPhysicalModel': null,
        'RenderPhysicalShape': null,
        'RenderPointerListener': null,
        'RenderPositionedBox': null,
        'RenderRepaintBoundary': null,
        'RenderSemanticsAnnotations': null,
        'RenderSemanticsGestureHandler': null,
        'RenderShrinkWrappingViewport': null,
        'RenderSliverConstrainedCrossAxis': null,
        'RenderSliverFillRemaining': null,
        'RenderSliverFillRemainingWithScrollable': null,
        'RenderSliverFillViewport': null,
        'RenderSliverFixedExtentList': null,
        'RenderSliverGrid': null,
        'RenderSliverIgnorePointer': null,
        'RenderSliverList': null,
        'RenderSliverOffstage': null,
        'RenderSliverOverlapAbsorber': null,
        'RenderSliverOverlapInjector': null,
        'RenderSliverPadding': null,
        'RenderSliverToBoxAdapter': null,
        'RenderStack': null,
        'RenderTapRegion': null,
        'RenderTapRegionSurface': null,
        'RenderTransform': null,
        'RenderViewport': null,
        'RestorableBool': null,
        'RestorableCupertinoTabController': null,
        'RestorableDateTimeN': null,
        'RestorableNum<int>': null,
        'RestorableStringN': null,
        'RestorableTextEditingController': null,
        'RestorationManager': null,
        'ScaffoldMessengerState': null,
        'ScaffoldState': null,
        'ScrollController': null,
        'ScrollPositionWithSingleContext': null,
        'ScrollableState': null,
        'ScrollbarPainter': null,
        'SearchController': null,
        'SelectableRegionState': null,
        'ShortcutManager': null,
        'SingleChildRenderObjectElement': null,
        'SliverMultiBoxAdaptorElement': null,
        'SliverOverlapAbsorberHandle': null,
        'SliverReorderableListState': null,
        'SnapshotController': null,
        'StatefulElement': null,
        'StatelessElement': null,
        'TabController': null,
        'TestDataSource': null,
        'TestRestorationManager': null,
        'TestShortcutManager': null,
        'TextEditingController': null,
        'TooltipState': null,
        'UndoHistoryController': null,
        'UndoHistoryState<TextEditingValue>': null,
        'UnsettableController': null,
        'ValueNotifier<MagnifierInfo>': null,
        'ValueNotifier<bool>': null,
        'ValueNotifier<int>': null,
        '_AnimatedSizeState': null,
        '_ButtonStyleState': null,
        '_CalendarDatePickerState': null,
        '_CaretPainter': null,
        '_CupertinoAppState': null,
        '_CupertinoBackGestureDetectorState<dynamic>': null,
        '_CupertinoButtonState': null,
        '_CupertinoDesktopTextSelectionToolbarButtonState': null,
        '_CupertinoPickerState': null,
        '_CupertinoScrollbarState': null,
        '_CupertinoSearchTextFieldState': null,
        '_CupertinoTabScaffoldState': null,
        '_CupertinoTextFieldState': null,
        '_CupertinoTextFormFieldRowState': null,
        '_CupertinoTextSelectionToolbarButtonState': null,
        '_CupertinoTextSelectionToolbarContentState': null,
        '_CupertinoTextSelectionToolbarItemsElement': null,
        '_DatePickerDialogState': null,
        '_DateRangePickerDialogState': null,
        '_DayState': null,
        '_DragTargetState<int>': null,
        '_DraggableState<Object>': null,
        '_DraggableState<int>': null,
        '_DropdownMenuState<TestMenu>': null,
        '_DropdownMenuState<int>': null,
        '_ExpandingBoxState': null,
        '_FixedExtentScrollPosition': null,
        '_FixedExtentScrollableState': null,
        '_FocusTraversalGroupNode': null,
        '_FocusableActionDetectorState': null,
        '_GeometryListenerState': null,
        '_History': null,
        '_HistoryProperty': null,
        '_InheritedNotifierElement<FocusNode>': null,
        '_InheritedNotifierElement<ValueNotifier<int>>': null,
        '_InkResponseState': null,
        '_InputBorderGap': null,
        '_InputDatePickerFormFieldState': null,
        '_InputDateRangePickerState': null,
        '_LayoutBuilderElement<BoxConstraints>': null,
        '_ListWheelScrollViewState': null,
        '_LocalizationsState': null,
        '_MaterialAppState': null,
        '_MaterialScrollbarState': null,
        '_MaterialState': null,
        '_MenuAnchorState': null,
        '_MenuBarAnchorState': null,
        '_MenuItemButtonState': null,
        '_ModalScopeState<dynamic>': null,
        '_MonthPickerState': null,
        '_MultiChildComponentElement': null,
        '_NestedScrollController': null,
        '_NestedScrollPosition': null,
        '_NotificationElement<KeepAliveNotification>': null,
        '_NotificationElement<LayoutChangedNotification>': null,
        '_NotificationElement<NavigationNotification>': null,
        '_NotificationElement<OverscrollIndicatorNotification>': null,
        '_NotificationElement<ScrollMetricsNotification>': null,
        '_NotificationElement<ScrollNotification>': null,
        '_NotificationElement<ScrollUpdateNotification>': null,
        '_OffstageElement': null,
        '_OverlayEntryWidgetState': null,
        '_OverlayPortalElement': null,
        '_PagePosition': null,
        '_PageViewState': null,
        '_RadioPainter': null,
        '_RadioState<int>': null,
        '_RangeSliderState': null,
        '_RawAutocompleteState<String>': null,
        '_RawAutocompleteState<User>': null,
        '_RenderAppBarTitleBox': null,
        '_RenderButtonBarRow': null,
        '_RenderColoredBox': null,
        '_RenderCompositionCallback': null,
        '_RenderCupertinoPickerSemantics': null,
        '_RenderCupertinoTextSelectionToolbarItems': null,
        '_RenderCupertinoTextSelectionToolbarShape': null,
        '_RenderDecoration': null,
        '_RenderDeferredLayoutBox': null,
        '_RenderDropdownMenuBody': null,
        '_RenderExclusiveMouseRegion': null,
        '_RenderFlexibleSpaceHeaderOpacity': null,
        '_RenderInkFeatures': null,
        '_RenderInputPadding': null,
        '_RenderLayoutBuilder': null,
        '_RenderLayoutSurrogateProxyBox': null,
        '_RenderListTile': null,
        '_RenderMergeableMaterialListBody': null,
        '_RenderOverflowBar': null,
        '_RenderRangeSlider': null,
        '_RenderScrollSemantics': null,
        '_RenderSingleChildViewport': null,
        '_RenderSlider': null,
        '_RenderSliverFloatingPersistentHeaderForWidgets': null,
        '_RenderSliverFloatingPinnedPersistentHeaderForWidgets': null,
        '_RenderSliverFractionalPadding': null,
        '_RenderSliverPinnedPersistentHeaderForWidgets': null,
        '_RenderSliverPrototypeExtentList': null,
        '_RenderSliverScrollingPersistentHeaderForWidgets': null,
        '_RenderSnapshotWidget': null,
        '_RenderTextSelectionToolbarItemsLayout': null,
        '_RenderTheater': null,
        '_RenderValueIndicator': null,
        '_RenderVisibility': null,
        '_ReorderableListViewState': null,
        '_RestorableAutovalidateMode': null,
        '_RestorableDatePickerEntryMode': null,
        '_RestorableScrollOffset': null,
        '_RestorationScopeState': null,
        '_ScaffoldGeometryNotifier': null,
        '_SearchAnchorState': null,
        '_SearchBarState': null,
        '_SearchPageRoute<String>': null,
        '_SearchPageState<String>': null,
        '_SearchViewRoute': null,
        '_SelectableRegionContainerDelegate': null,
        '_SelectableTextState': null,
        '_SelectionHandleOverlayState': null,
        '_ShortcutsState': null,
        '_SingleChildViewportElement': null,
        '_SliderState': null,
        '_SliverAppBarState': null,
        '_SliverOffstageElement': null,
        '_SliverPersistentHeaderElement': null,
        '_SliverPrototypeExtentListElement': null,
        '_StatefulBuilderState': null,
        '_StepperState': null,
        '_SubmenuButtonState': null,
        '_TabBarScrollController': null,
        '_TabBarScrollPosition': null,
        '_TabBarState': null,
        '_TabLabelBarRenderer': null,
        '_TextFieldState': null,
        '_TextFormFieldState': null,
        '_TextHighlightPainter': null,
        '_TextSelectionGestureDetectorState': null,
        '_TextSelectionToolbarItemsLayoutElement': null,
        '_TextSelectionToolbarOverflowableState': null,
        '_TextSelectionToolbarTrailingEdgeAlignRenderBox': null,
        '_TextSpanEditingController': null,
        '_TheaterElement': null,
        '_TransformedEditableTextState': null,
        '_UbiquitousInheritedElement': null,
        '_ViewContentState': null,
        '_ViewportElement': null,
        '_WidgetWithNoVisitChildrenElement': null,
        '_WidgetsAppState': null,
        '_ZoomEnterTransitionPainter': null,
        '_ZoomExitTransitionPainter': null,
      },
      notDisposed: <String, int?>{
        'AnimationController': null,
        'OverlayEntry': null,
      },
    );

  // Enable golden file testing using Skia Gold.
  return flutter_goldens.testExecutable(testMain);
}
