/// Flutter icons AssetAudioPlayer
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AssetAudioPlayer
///      fonts:
///       - asset: fonts/AssetAudioPlayer.ttf
///
///
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class AssetAudioPlayerIcons {
  AssetAudioPlayerIcons._();

  static const _kFontFam = 'AssetAudioPlayer';

  static const IconData play = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData stop = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData pause = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData to_end = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData to_start = IconData(0xe804, fontFamily: _kFontFam);
}
