name: platform_channel_swift

environment:
  sdk: ^3.11.0-0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  material_ui: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

# PUBSPEC CHECKSUM: 2rmgtd
