name: dev_tools
description: Various repository development tools for flutter.

environment:
  sdk: ^3.11.0-0

resolution: workspace

dependencies:
  archive: any
  args: any
  convert: any
  http: any
  meta: any
  path: any
  process: any
  process_runner: any
  pub_semver: any
  yaml: any

  collection: any
  file: any
  platform: any
  yaml_edit: any
  skills_lint: ^0.5.1
  logging: ^1.3.0

dev_dependencies:
  test: any
  test_api: any


  matcher: any

# PUBSPEC CHECKSUM: e9gs4
