#!/usr/bin/env bash
# Copyright 2014 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Repackages the Gradle wrapper launcher (gradlew, gradlew.bat and
# gradle/wrapper/gradle-wrapper.jar) that the Flutter tool injects into Android
# projects that don't already have one, uploads it to flutter_infra_release,
# and updates bin/internal/gradle_wrapper.version to point at it.
#
# The launcher is generated by an official Gradle distribution, so it includes
# upstream fixes such as the `Enable-Native-Access` manifest attribute added in
# Gradle 8.14 (https://github.com/gradle/gradle/issues/31625).
#
# Requires a JDK supported by the requested Gradle version (JAVA_HOME or java on
# PATH), curl and unzip. Uploading requires gsutil.py and write access to
# gs://flutter_infra_release.
#
# Usage:
#   dev/tools/repackage_gradle_wrapper.sh <gradle-version> [--no-upload]
#
# Example:
#   dev/tools/repackage_gradle_wrapper.sh 9.5.0
#
# With --no-upload, the tarball is left in bin/cache/gradle-wrapper-temp and
# bin/internal/gradle_wrapper.version is still updated, so the result can be
# inspected before uploading.

set -e

GRADLE_VERSION=""
UPLOAD=true
for arg in "$@"; do
  case "$arg" in
    --no-upload)
      UPLOAD=false
      ;;
    -*)
      echo "Unknown option: $arg" >&2
      exit 1
      ;;
    *)
      GRADLE_VERSION="$arg"
      ;;
  esac
done

if [[ ! "$GRADLE_VERSION" =~ ^[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
  echo "Usage: $0 <gradle-version> [--no-upload]   (for example: $0 9.5.0)" >&2
  exit 1
fi

case "$(uname -s)" in
  Darwin)
    SHASUM="shasum"
    SHA256SUM="shasum -a 256"
    ;;
  *)
    SHASUM="sha1sum"
    SHA256SUM="sha256sum"
    ;;
esac

function follow_links() {
  cd -P "${1%/*}"
  file="$PWD/${1##*/}"
  while [ -h "$file" ]; do
    # On Mac OS, readlink -f doesn't work.
    cd -P "${file%/*}"
    file="$(readlink "$file")"
    cd -P "${file%/*}"
    file="$PWD/${file##*/}"
  done
  echo "$PWD/${file##*/}"
}

# Convert a filesystem path to a format usable by Dart's URI parser.
function path_uri() {
  # Reduce multiple leading slashes to a single slash.
  echo "$1" | sed -E -e "s,^/+,/,"
}

# Verifies that the file at $1 has the SHA-256 checksum published at URL $2.
function verify_sha256() {
  local expected
  local actual
  expected="$(curl --fail --silent --show-error --location "$2")"
  actual="$($SHA256SUM "$1" | cut -d' ' -f1)"
  if [[ "$expected" != "$actual" ]]; then
    echo "Checksum mismatch for $1: expected $expected, got $actual" >&2
    exit 1
  fi
}

PROG_NAME="$(path_uri "$(follow_links "$BASH_SOURCE")")"
BIN_DIR="$(cd "${PROG_NAME%/*}" ; pwd -P)"
FLUTTER_ROOT="$(cd "${BIN_DIR}/../.." ; pwd -P)"

WRAPPER_VERSION_PATH="$FLUTTER_ROOT/bin/internal/gradle_wrapper.version"
WRAPPER_TEMP_DIR="$FLUTTER_ROOT/bin/cache/gradle-wrapper-temp"

DISTRIBUTIONS_URL="https://services.gradle.org/distributions"
DIST_NAME="gradle-${GRADLE_VERSION}"
DIST_URL="${DISTRIBUTIONS_URL}/${DIST_NAME}-bin.zip"

echo "Downloading Gradle ${GRADLE_VERSION}..."
rm -rf "$WRAPPER_TEMP_DIR"
mkdir -p "$WRAPPER_TEMP_DIR"
curl --fail --location --output "${WRAPPER_TEMP_DIR}/dist.zip" "${DIST_URL}" 2>&1
verify_sha256 "${WRAPPER_TEMP_DIR}/dist.zip" "${DIST_URL}.sha256"
unzip -q "${WRAPPER_TEMP_DIR}/dist.zip" -d "${WRAPPER_TEMP_DIR}/dist"

echo
echo "Generating the Gradle wrapper..."
GEN_DIR="${WRAPPER_TEMP_DIR}/gen"
mkdir "$GEN_DIR"
touch "${GEN_DIR}/settings.gradle"
(
  cd "$GEN_DIR"
  "${WRAPPER_TEMP_DIR}/dist/${DIST_NAME}/bin/gradle" wrapper \
    --gradle-version "$GRADLE_VERSION" \
    --no-daemon \
    --quiet
)

WRAPPER_JAR="${GEN_DIR}/gradle/wrapper/gradle-wrapper.jar"
verify_sha256 "$WRAPPER_JAR" "${DISTRIBUTIONS_URL}/${DIST_NAME}-wrapper.jar.sha256"

# Launchers older than Gradle 8.14 don't grant native access to the JVM they
# start, which makes JDK 24+ print warnings (and future JDKs fail).
if ! unzip -p "$WRAPPER_JAR" META-INF/MANIFEST.MF | grep -q "Enable-Native-Access"; then
  echo "gradle-wrapper.jar is missing the Enable-Native-Access manifest attribute." >&2
  echo "Use Gradle 8.14 or newer." >&2
  exit 1
fi

echo
echo "Repackaging files..."
# Keep the layout the Flutter tool expects (see GradleWrapper in
# packages/flutter_tools/lib/src/flutter_cache.dart). The tool deletes NOTICE
# after download, so it isn't copied into projects.
REPACK_DIR="${WRAPPER_TEMP_DIR}/repack"
mkdir -p "${REPACK_DIR}/gradle/wrapper"
cp -p "${GEN_DIR}/gradlew" "${GEN_DIR}/gradlew.bat" "${REPACK_DIR}/"
cp -p "$WRAPPER_JAR" "${REPACK_DIR}/gradle/wrapper/"
cp -p "${WRAPPER_TEMP_DIR}/dist/${DIST_NAME}/LICENSE" "${REPACK_DIR}/NOTICE"

pushd "$REPACK_DIR" > /dev/null
STAMP=`for h in $(find . -type f | LC_ALL=C sort); do $SHASUM $h; done | $SHASUM | cut -d' ' -f1`
echo "Packaged files:"
tar cvzf ../gradle-wrapper.tgz *
popd > /dev/null

echo
echo "Content hash: $STAMP"
if [[ "$UPLOAD" == true ]]; then
  echo "Uploading repackaged gradle wrapper..."
  gsutil.py cp -n "$WRAPPER_TEMP_DIR/gradle-wrapper.tgz" "gs://flutter_infra_release/gradle-wrapper/$STAMP/gradle-wrapper.tgz"
fi

echo "flutter_infra_release/gradle-wrapper/$STAMP/gradle-wrapper.tgz" > "$WRAPPER_VERSION_PATH"

echo
if [[ "$UPLOAD" == true ]]; then
  rm -rf "$WRAPPER_TEMP_DIR"
  echo "All done. Updated bin/internal/gradle_wrapper.version, don't forget to commit!"
else
  echo "Skipped upload. The tarball is at $WRAPPER_TEMP_DIR/gradle-wrapper.tgz."
  echo "Upload it to gs://flutter_infra_release/gradle-wrapper/$STAMP/gradle-wrapper.tgz"
  echo "before committing bin/internal/gradle_wrapper.version."
fi
