#!/usr/bin/env python
# Copyright (c) 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import subprocess

from webkitpy.common.system import filesystem
from webkitpy.common.webkit_finder import WebKitFinder

finder = WebKitFinder(filesystem.FileSystem())

subprocess.call([
    'download_from_google_storage',
    '--no_resume',
    '--no_auth',
    '--bucket', 'mojo',
    '--sha1_file', finder.path_from_chromium_base('sky', 'tools', 'skygo', 'sky_server.sha1'),
    '--output', finder.path_from_chromium_base('out', 'downloads', 'sky_server')
])
