// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// http://www.whatwg.org/specs/web-apps/current-work/multipage/the-canvas-element.html#MouseEvent-partial

[
    RuntimeEnabled=ExperimentalCanvasFeatures
] partial interface MouseEvent {
    readonly attribute DOMString? region;
};
