// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:convert';
import 'dart:typed_data';

import 'package:test/bootstrap/browser.dart';
import 'package:test/test.dart';
import 'package:ui/src/engine.dart';
import 'package:ui/ui.dart' as ui;

import '../common/test_data.dart';
import 'common.dart';

void main() {
  internalBootstrapBrowserTest(() => testMain);
}

void testMain() {
  group('CanvasKit shaders', () {
    setUpCanvasKitTest();

    test('Image shader initialize/dispose cycle', () async {
      final EngineImage image = await createImageFromBytes(kTransparentImage);
      final imageShader = ui.ImageShader(
        image,
        ui.TileMode.clamp,
        ui.TileMode.repeated,
        Float64List.fromList(Matrix4.diagonal3Values(1, 2, 3).storage),
      ) as EngineImageShader;
      final ckShader = imageShader.getBackendShader(ui.FilterQuality.none) as CkImageShader;
      expect(ckShader, isA<CkImageShader>());

      expect(ckShader.skShader, isNotNull);
      expect(ckShader.debugDisposed, false);
      expect(imageShader.getBackendShader(ui.FilterQuality.none), same(ckShader));
      expect(image.debugDisposed, false);
      imageShader.dispose();
      expect(ckShader.debugDisposed, true);
      expect(image.debugDisposed, false);

      // Disposing again should be a no-op and not crash.
      imageShader.dispose();
      expect(ckShader.debugDisposed, true);
      expect(image.debugDisposed, false);
    });

    test('FragmentShader isGradient is false', () {
      const minimalShaderJson = r'''
{
  "sksl": {
    "entrypoint": "main",
    "shader": "half4 main(float2 fragCoord) {return half4(1.0, 0.0, 0.0, 1.0);}",
    "stage": 1,
    "uniforms": []
  }
}
''';
      final Uint8List data = utf8.encode(minimalShaderJson);
      final program = CkFragmentProgram.fromBytes('test', data);
      final fragmentShader = program.fragmentShader() as EngineFragmentShader;
      expect(fragmentShader.getBackendShader(ui.FilterQuality.none).isGradient, isFalse);
      fragmentShader.dispose();
    });

    test('FragmentShader sampler lifecycle and cleanup', () async {
      const textureShaderJson = r'''
{
  "format_version": 1,
  "sksl": {
    "entrypoint": "texture_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 u_size;\nuniform shader u_texture;\nuniform half2 u_texture_size;\n\nvec4 frag_color;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    frag_color = u_texture.eval(u_texture_size * ( FLT_flutter_local_FlutterFragCoord() / u_size));\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return frag_color;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "u_size",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 1,
        "name": "u_texture",
        "rows": 1,
        "type": 12
      }
    ]
  }
}
''';
      final Uint8List data = utf8.encode(textureShaderJson);
      final program = CkFragmentProgram.fromBytes('texture_test', data);
      final fragmentShader = program.fragmentShader() as EngineFragmentShader;

      final EngineImage image1 = await createImageFromBytes(kTransparentImage);
      final EngineImage image2 = await createImageFromBytes(kTransparentImage);

      fragmentShader.setImageSampler(0, image1);
      final BackendImageShader sampler1 = fragmentShader.debugImageSamplers[0]!;
      expect((sampler1 as CkImageShader).debugDisposed, isFalse);

      // Overwriting sampler at index 0 should dispose the old sampler.
      fragmentShader.setImageSampler(0, image2);
      final BackendImageShader sampler2 = fragmentShader.debugImageSamplers[0]!;
      expect(sampler1.debugDisposed, isTrue);
      expect((sampler2 as CkImageShader).debugDisposed, isFalse);

      // Disposing fragmentShader should dispose sampler2.
      fragmentShader.dispose();
      expect(sampler2.debugDisposed, isTrue);
    });
  });
}
