// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/// The `HookIcons` font that `hook/build.dart` writes into its output directory
/// and registers as a font asset, encoded as base64 so that this repository
/// does not have to contain a binary file.
///
/// It is a subset of `MaterialIcons-Regular.otf` from the Flutter SDK
/// (https://github.com/google/material-design-icons, Apache License 2.0) with
/// only the "add" glyph at U+E047, produced with the SDK's `font-subset` tool.
const String kHookIconsFontBase64 =
    'T1RUTwAJAIAAAwAQQ0ZGIKAs+RcAAAG8AAAAo09TLzIjOzQLAAABXAAAAGBjbWFwAAzgmgAAAPAA'
    'AAA0aGVhZB+SECwAAAEkAAAANmhoZWECAQICAAAAzAAAACRobXR4AgAAAAAAAJwAAAAGbWF4cAAC'
    'UAAAAACkAAAABm5hbWUZFDSwAAACYAAAAXZwb3N0AAMAAAAAAKwAAAAgAgAAAAAAAAAAAFAAAAIA'
    'AAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAIAAAAAAAIAAAAAAAAAAAEAAAAA'
    'AAAAAAAAAAAAAAABAAAAAgAAAAMAAAAUAAMAAQAAABQABAAgAAAABAAEAAEAAOBH//8AAOBH//8f'
    'ugABAAAAAAABAAAAAQAA5piY6F8PPPUAAwIAAAAAAN89c4YAAAAA3z5brgAAAAACAAIAAAAAAwAC'
    'AAAAAAAAAAQCAAGQAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAA'
    'AAAAAAAAAD8/Pz8AgOBH4EcCAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAIAAAAQAEBAABAQETQWxs'
    'M1BJY29ucy1SZWd1bGFyAAEBATUcAYcCHqABlTEl/4uLHqABlTEl/4uLDAeLi/iU+JQFHQAAAHoP'
    'HAAAHQAAAAASHQAAAH0RAAIBARMfQWxsM1BJY29ucy1SZWd1bGFyYWRkX2Jhc2VsaW5lAAAAAYgA'
    'AgEBBCH4lA74lPgp938V+xT7FGH3FPsUtfcU9xS1+xT3FGEGDgAAAAAHAFoAAwABBAkAAABeAL4A'
    'AwABBAkAAQAcAKIAAwABBAkAAgAOAJQAAwABBAkAAwA2AF4AAwABBAkABAAqADQAAwABBAkABQA0'
    'AAAAAwABBAkABgAqADQAMgAwADIAMgAtADAAOQAtADAANgBUADEANQA6ADAAMAA6ADMAOAAuADgA'
    'MQA5ADkAMAAzAE0AYQB0AGUAcgBpAGEAbABJAGMAbwBuAHMALQBSAGUAZwB1AGwAYQByAE0AYQB0'
    'AGUAcgBpAGEAbAAgAEkAYwBvAG4AcwAgADoAIAAyADAAMgAyAC0AMAA5AC0AMAA3AFIAZQBnAHUA'
    'bABhAHIATQBhAHQAZQByAGkAYQBsACAASQBjAG8AbgBzAEMAbwBwAHkAcgBpAGcAaAB0ACAAMgAw'
    'ADEAOQAgAEcAbwBvAGcAbABlACAATABMAEMALgAgAEEAbABsACAAUgBpAGcAaAB0AHMAIABSAGUA'
    'cwBlAHIAdgBlAGQALgAA';
