name: api_multiwindow

environment:
  sdk: ^3.9.0-0

# See https://flutter.dev/to/flutter-update-packages
checksum: f13f5c8f94f6e7e29da1f2c3e5a6b7d8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
