name: api_multiwindow

environment:
  sdk: ^3.9.0-0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

# PUBSPEC CHECKSUM: 7ggeci
