name: flutter_tools_extension_linux_prototype
description: Prototype Linux extension for Flutter tools extensibility.
resolution: workspace

environment:
  sdk: ^3.11.0-0

dependencies:
  meta: 1.19.0
  flutter_tools_core:
    path: ../flutter_tools_core
  flutter_tools_extension:
    path: ../flutter_tools_extension

dev_dependencies:
  test: 1.31.1

# PUBSPEC CHECKSUM: i74lku
