# Copyright 2013 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//flutter/testing/testing.gni")

source_set("vulkan_queue_guard") {
  sources = [
    "vulkan_queue_guard.cc",
    "vulkan_queue_guard.h",
  ]

  public_deps = [
    "//flutter/fml",
    "//flutter/third_party/vulkan-deps/vulkan-headers/src:vulkan_headers",
  ]

  public_configs = [ "//flutter:config" ]
}

if (enable_unittests) {
  executable("vulkan_queue_guard_unittests") {
    testonly = true

    sources = [ "vulkan_queue_guard_unittests.cc" ]

    deps = [
      ":vulkan_queue_guard",
      "//flutter/fml",
      "//flutter/third_party/googletest:gtest",
      "//flutter/third_party/googletest:gtest_main",
    ]
  }
}
