# Copyright 2013 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: coverage

on:
  push:
    branches:
      - master
    paths:
      - 'packages/flutter/**'

permissions: read-all

jobs:
  build:
    name: coverage
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'flutter/flutter' }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: bootstrap Flutter tool
        run: ./bin/flutter --version
      - name: ./bin/flutter test --coverage
        run: pushd packages/flutter;../../bin/flutter test --coverage -j 1;popd
      - name: upload coverage
        if: ${{ always() }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          files: packages/flutter/coverage/lcov.info
          verbose: true
