# Copyright 2013 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: coverage

on:
  push:
    branches:
      - master
    paths:
      - 'packages/flutter/**'

permissions: read-all

jobs:
  build:
    name: coverage
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'flutter/flutter' }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: bootstrap Flutter tool
        run: ./bin/flutter --version
      - name: ./bin/flutter test --coverage
        run: pushd packages/flutter;../../bin/flutter test --coverage -j 1;popd
      - name: upload coverage
        if: ${{ always() }}
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2
        with:
          files: packages/flutter/coverage/lcov.info
          verbose: true
