name: Scheduled Localization Update Issue
on:
  schedule:
    # Triggers quarterly at 09:40 UTC on the 2nd of Feb, May, Aug, Nov
    # Use https://crontab.guru to test and adjust schedules
    # Actions can be delayed or dropped during heavy load periods,
    # e.g. top of the hour, first of the month. Offset accordingly.
    - cron: 40 09 2 2,5,8,11 *
  workflow_dispatch:

jobs:
  create_issue:
    name: Create localization update issue
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'flutter/flutter' }}
    permissions:
      issues: write
    steps:
      - name: Create localization update issue
        run: |
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY")
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: '[Automated Task] Quarterly Localizations Update (flutter_localizations)'
          ASSIGNEES: QuncCccccc
          LABELS: automated task,a: internationalization,team-framework
          BODY: |
            ### Quarterly Localization Update

            **Context**: Ahead of the upcoming stable release cut, localized strings need to be synchronized from the internal console into the framework.

            ### Checklist
            - [ ] Check for any new strings that need to be sent upstream for translation.
            - [ ] Pull latest translations from internal translation console.
            - [ ] Update localizations in `flutter_localizations`, Material (`material_ui`), and Cupertino (`cupertino_ui`).
              - [ ] **Follow-up check**: Note that updates to Material or Cupertino localizations might need to wait for the stable roll. If so, file a new follow-up issue to complete after the stable roll.
            - [ ] Run test suite for localizations.
            - [ ] Open PR to close this issue.

            *This issue was automatically generated by GitHub Actions workflow.*
