name: Tree Analyze

on:
  pull_request:
    branches: [master]
  merge_group:
    branches: [master]

jobs:
  Tree_analyze:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 130

    steps:
      # Note: we must check out the tree for the composite action to be available
      - name: Checkout code
        if: env.ACT != 'true'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          persist-credentials: false

      - name: Checkout code (act local)
        if: env.ACT
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Wait for Engine Build
        uses: ./.github/actions/wait-for-engine-build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/composite-flutter-setup

      - name: Run Analyze
        run: |
          SHARD=analyze LUCI_CI=true dart --enable-asserts dev/bots/test.dart
